import { ArrowLeftRight, RotateCcw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useData, useFilters } from '../state';
import { aggregateRecords, calculateMatchupMetrics, getHeadToHeadMatchup, getPlayerById, leagueAverage } from '../lib/api';
import { Actions, Empty, Field, Metric, PageHead, PlayerIdentity, Quality, SearchPlayers, number, signed } from '../components/Common';
import { possessionSteps, normalizePossessions } from '../lib/filters';
import { Button } from '../components/ui/button';

function PlayerPicker({ label, playerId, otherId, team, onTeam, onChoose, onClear }:{label:string;playerId:string;otherId:string;team:string;onTeam:(team:string)=>void;onChoose:(id:string)=>void;onClear:()=>void}) {
  const data=useData(); const player=getPlayerById(data,playerId); const available=data.players.filter(p=>p.id!==otherId);
  return <section className="comparison-picker-card"><div className="picker-heading"><span>{label}</span><small>{player?'已选择':'等待选择'}</small></div><Field label="球队筛选"><select value={team} onChange={e=>onTeam(e.target.value)}><option value="">所有球队</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.abbreviation} {t.chineseName}</option>)}</select></Field>{player?<div className="selected-player"><PlayerIdentity player={player} large/><Button variant="ghost" onClick={onClear}>清除</Button></div>:<><SearchPlayers label="搜索球员" team={team} onChoose={p=>onChoose(p.id)}/><p className="picker-hint">支持姓名、中文名、缩写和球队搜索；共 {available.filter(p=>!team||p.teamId===team).length} 位可选球员。</p></>}</section>;
}
function ComparisonSlider({value,onChange}:{value:number;onChange:(value:number)=>void}) { return <Field label={`Minimum matchup possessions: ${value}`}><input className="possessions-slider" type="range" min={10} max={50} step={5} value={value} list="comparison-possessions" onChange={e=>onChange(normalizePossessions(Number(e.target.value)))} /><span className="range-ticks">{possessionSteps.map(v=><span key={v}>{v}</span>)}</span><datalist id="comparison-possessions">{possessionSteps.map(v=><option key={v} value={v}/>)}</datalist></Field>; }

export function ComparisonPage(){
  const data=useData(); const {filters,params,setParams,update}=useFilters();
  const leftId=params.get('leftPlayer')??params.get('a')??''; const rightId=params.get('rightPlayer')??params.get('b')??'';
  const left=getPlayerById(data,leftId); const right=getPlayerById(data,rightId);
  const setPlayer=(key:'leftPlayer'|'rightPlayer',id:string)=>{const next=new URLSearchParams(params);next.set(key,id);next.delete(key==='leftPlayer'?'a':'b');setParams(next,{replace:true});};
  const clear=()=>{const next=new URLSearchParams(params);['leftPlayer','rightPlayer','a','b','teamA','teamB'].forEach(k=>next.delete(k));setParams(next,{replace:true});};
  const swap=()=>{if(!left||!right)return;const next=new URLSearchParams(params);next.set('leftPlayer',right.id);next.set('rightPlayer',left.id);next.delete('a');next.delete('b');setParams(next,{replace:true});};
  const h=left&&right?getHeadToHeadMatchup(data,left.id,right.id,filters):{a:[],b:[]}; const ar=aggregateRecords(h.a),br=aggregateRecords(h.b),avg=leagueAverage(data,filters); const am=ar?calculateMatchupMetrics(ar,avg):null,bm=br?calculateMatchupMetrics(br,avg):null;
  return <><PageHead eyebrow="HEAD TO HEAD" title="球员比较" description="选择两名球员，查看他们在彼此直接防守下的进攻表现。筛选状态会保存在 URL，方便分享和复现。"/>
    <section className="comparison-controls"><div className="comparison-pickers"><PlayerPicker label="左侧球员" playerId={leftId} otherId={rightId} team={params.get('teamA')??''} onTeam={team=>{const next=new URLSearchParams(params);if(team)next.set('teamA',team);else next.delete('teamA');setParams(next,{replace:true});}} onChoose={id=>setPlayer('leftPlayer',id)} onClear={()=>{const next=new URLSearchParams(params);next.delete('leftPlayer');next.delete('a');setParams(next,{replace:true});}}/><div className="comparison-swap"><span>VS</span><Button aria-label="交换左右球员" onClick={swap} disabled={!left||!right}><ArrowLeftRight size={18}/>交换左右</Button></div><PlayerPicker label="右侧球员" playerId={rightId} otherId={leftId} team={params.get('teamB')??''} onTeam={team=>{const next=new URLSearchParams(params);if(team)next.set('teamB',team);else next.delete('teamB');setParams(next,{replace:true});}} onChoose={id=>setPlayer('rightPlayer',id)} onClear={()=>{const next=new URLSearchParams(params);next.delete('rightPlayer');next.delete('b');setParams(next,{replace:true});}}/></div>
      <div className="comparison-filters"><Field label="赛季"><select value={filters.season} onChange={e=>update({season:e.target.value})}>{data.seasons.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="比赛类型"><select value={filters.type} onChange={e=>update({type:e.target.value as 'regular'|'playoffs'})}><option value="regular">常规赛</option><option value="playoffs">季后赛</option></select></Field><ComparisonSlider value={filters.minPossessions} onChange={minPossessions=>update({minPossessions})}/><Button onClick={clear}><RotateCcw size={15}/>清除比较</Button></div></section>
    {!left||!right?<Empty title={left?'再选择一名球员':'先选择两名球员'} message={left?`${left.shortName} 已准备好，请在右侧选择对手。`:'左右两侧分别选择一名球员后，页面会自动展示双向对位结果。'} />:<><section className="versus-cards"><article><PlayerIdentity player={left} large/><p>{left.shortName} 进攻面对 {right.shortName}</p><strong>{number(am?.pointsPer100)}</strong><span>每 100 对位回合得分</span>{ar&&<Quality quality={am!.sampleQuality} possessions={ar.matchupPossessions}/>}</article><span className="versus">VS</span><article><PlayerIdentity player={right} large/><p>{right.shortName} 进攻面对 {left.shortName}</p><strong>{number(bm?.pointsPer100)}</strong><span>每 100 对位回合得分</span>{br&&<Quality quality={bm!.sampleQuality} possessions={br.matchupPossessions}/>}</article></section><div className="metrics-grid"><Metric label={`${left.shortName} 进攻`} value={number(am?.pointsPer100)} unit="/100" basis={`${ar?.matchupPossessions??0} 回合`} help="得分 ÷ 对位回合 × 100。" delta={am?.pointsPer100!=null&&avg!=null?am.pointsPer100-avg:null}/><Metric label={`${right.shortName} 进攻`} value={number(bm?.pointsPer100)} unit="/100" basis={`${br?.matchupPossessions??0} 回合`} help="得分 ÷ 对位回合 × 100。" delta={bm?.pointsPer100!=null&&avg!=null?bm.pointsPer100-avg:null}/><Metric label="Efficiency Edge" value={am?.pointsPer100!=null&&bm?.pointsPer100!=null?signed(am.pointsPer100-bm.pointsPer100):'—'} unit="/100" basis="左侧减右侧" help="正值代表左侧球员在当前样本中的原始效率更高。"/><Metric label="联盟平均" value={number(avg)} unit="/100" basis="当前覆盖数据加权值" help="当前数据集均值，不代表完整官方联盟均值。"/><Metric label="样本质量" value={ar&&br&&ar.matchupPossessions>=filters.minPossessions&&br.matchupPossessions>=filters.minPossessions?'可比较':'谨慎'} basis={`最低门槛 ${filters.minPossessions} 回合`} help="样本等级仅按回合数量分级，不代表统计置信度。"/><Metric label="数据更新时间" value={data.updatedAt.slice(0,10)} basis={data.mode==='live'?'LIVE DATA':'DEMO DATA'} help="数据通过 GitHub JSON 发布层提供。"/></div><section className="analysis-note"><h2>数据口径</h2><p>对位效率 = 得分 ÷（投篮出手 + 0.44 × 罚球出手 + 失误）。对位回合是追踪数据中两名球员直接匹配的回合；低样本结果需要谨慎解释，不能单独代表完整防守能力。</p></section><div className="actions"><Button asChild><Link to={`/players/${left.id}?season=${filters.season}`}>查看 {left.shortName} 画像</Link></Button><Button asChild><Link to={`/players/${right.id}?season=${filters.season}`}>查看 {right.shortName} 画像</Link></Button></div><Actions title={`${left.name} vs ${right.name}`} subtitle={`${filters.season} 直接对位`} metrics={[{label:'左侧 /100',value:number(am?.pointsPer100)},{label:'右侧 /100',value:number(bm?.pointsPer100)},{label:'Efficiency Edge',value:am?.pointsPer100!=null&&bm?.pointsPer100!=null?signed(am.pointsPer100-bm.pointsPer100):'—'}]} players={[left,right]}/></>}
  </>;
}
