import { useMemo, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { CalendarDays, CheckCircle2, Globe2, History, Rocket, Search, Shield, WalletCards } from 'lucide-react';
import { useData, useDataStatus } from '../state';
import { getRankings, getTeamStats, searchPlayers } from '../lib/api';
import { DataMethodNote, Empty, PageHead, Pagination, PlayerIdentity, PlayerLink, number } from '../components/Common';
import { Button } from '../components/ui/button';

function StatusCard({ label='数据状态' }: { label?: string }) {
  const status = useDataStatus();
  const unavailable = status.state === 'unavailable';
  const tone = status.state === 'live' || status.state === 'recently-updated' ? 'success' : unavailable ? 'warning' : 'muted';
  return <div className={`data-availability data-availability-${tone}`} role="status"><span className="status-dot" /><div><strong>{label}：{status.state === 'live' ? 'LIVE DATA' : status.state === 'recently-updated' ? 'RECENTLY UPDATED' : status.state === 'stale' ? 'STALE DATA' : status.state === 'demo' ? 'DEMO DATA' : 'DATA UNAVAILABLE'}</strong><small>{status.message ?? status.coverage} · 更新 {status.lastUpdated.slice(0, 10)}</small></div></div>;
}

export function PlayerDirectoryPage() {
  const data = useData(); const [params, setParams] = useSearchParams();
  const query = params.get('q') ?? ''; const team = params.get('team') ?? ''; const position = params.get('position') ?? ''; const page = Math.max(1, Number(params.get('page') ?? '1'));
  const filtered = useMemo(() => searchPlayers(data, query, team).filter((p) => !position || p.position === position).sort((a, b) => a.name.localeCompare(b.name)), [data, query, team, position]);
  const pageSize = 12; const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('page'); setParams(next, { replace: true }); };
  return <><PageHead eyebrow="PLAYER DIRECTORY" title="球员数据" description="浏览当前发布数据目录中的 NBA 球员、球队归属、位置和对位入口。" /><StatusCard /><DataMethodNote /><section className="directory-toolbar"><label className="field"><span><Search size={14} /> 搜索球员</span><input value={query} placeholder="姓名、中文名、缩写或球队" onChange={(e) => update('q', e.target.value)} /></label><label className="field"><span>球队</span><select value={team} onChange={(e) => update('team', e.target.value)}><option value="">全部球队</option>{data.teams.map((t) => <option key={t.id} value={t.id}>{t.abbreviation} · {t.chineseName}</option>)}</select></label><label className="field"><span>位置</span><select value={position} onChange={(e) => update('position', e.target.value)}><option value="">全部位置</option>{['G', 'F', 'C', 'G-F', 'F-C', 'Unknown'].map((p) => <option key={p}>{p}</option>)}</select></label></section><section className="directory-grid">{rows.map((player) => <article className="directory-card" key={player.id}><PlayerLink player={player} /><dl><div><dt>球员 ID</dt><dd>{player.id}</dd></div><div><dt>球队</dt><dd>{player.teamAbbreviation}</dd></div><div><dt>位置</dt><dd>{player.position}</dd></div><div><dt>对位入口</dt><dd><Link to={`/matchups/player/${player.id}`}>查看记录 →</Link></dd></div></dl></article>)}</section>{!rows.length && <Empty title="没有匹配的球员" message="请清除筛选，或使用英文姓名、中文名、球队缩写搜索。" />}<Pagination page={page} total={filtered.length} pageSize={pageSize} onChange={(next) => { const p = new URLSearchParams(params); p.set('page', String(next)); setParams(p, { replace: true }); }} /></>;
}

export function TeamDirectoryPage() {
  const data = useData(); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const pageSize = 12;
  const rows = data.teams.filter((t) => [t.id, t.name, t.chineseName, t.abbreviation].some((v) => v.toLowerCase().includes(query.toLowerCase()))).slice((page - 1) * pageSize, page * pageSize);
  return <><PageHead eyebrow="TEAM DIRECTORY" title="球队数据" description="查看 NBA 球队目录与已发布的球队统计入口；球队数据只显示当前数据集真实覆盖范围。" /><StatusCard /><section className="directory-toolbar"><label className="field"><span><Search size={14} /> 搜索球队</span><input value={query} placeholder="球队名称或缩写" onChange={(e) => { setQuery(e.target.value); setPage(1); }} /></label></section><section className="directory-grid team-directory">{rows.map((team) => { const stats = getTeamStats(data, team.id, { season: data.seasons[0] })[0]; return <article className="directory-card" key={team.id}><div className="team-mark" aria-hidden="true">{team.abbreviation.slice(0, 2)}</div><div><h3>{team.chineseName}</h3><p>{team.name} · {team.id}</p></div><dl><div><dt>进攻效率</dt><dd>{number(stats?.offensiveRating)}</dd></div><div><dt>防守效率</dt><dd>{number(stats?.defensiveRating)}</dd></div><div><dt>节奏</dt><dd>{number(stats?.pace)}</dd></div></dl><Link className="card-link" to={`/teams/${team.id}`}>查看球队详情 →</Link></article>; })}</section>{!rows.length && <Empty title="没有匹配的球队" message="请使用球队名称或缩写搜索。" />}<Pagination page={page} total={data.teams.filter((t) => [t.id, t.name, t.chineseName, t.abbreviation].some((v) => v.toLowerCase().includes(query.toLowerCase()))).length} pageSize={pageSize} onChange={setPage} /></>;
}

export function TeamDetailPage() {
  const data = useData(); const { teamId } = useParams(); const team = data.teams.find((t) => t.id === teamId); const stats = team ? getTeamStats(data, team.id, { season: data.seasons[0] })[0] : undefined;
  if (!team) return <Empty title="未找到球队" message="请从球队数据目录选择有效球队。"><Button asChild><Link to="/teams">返回球队数据</Link></Button></Empty>;
  const players = data.players.filter((p) => p.teamId === team.id);
  return <><PageHead eyebrow="TEAM PROFILE" title={`${team.chineseName} · ${team.abbreviation}`} description={`${team.name} 的球队目录、赛季效率和当前发布数据覆盖。`} /><StatusCard /><div className="metrics-grid"><article className="metric"><span className="metric-label">进攻效率</span><strong>{number(stats?.offensiveRating)}</strong><p>{data.seasons[0]} · 当前数据</p></article><article className="metric"><span className="metric-label">防守效率</span><strong>{number(stats?.defensiveRating)}</strong><p>数值越低通常代表限制得分更好</p></article><article className="metric"><span className="metric-label">节奏</span><strong>{number(stats?.pace)}</strong><p>当前覆盖赛季</p></article></div><section className="section"><div className="section-title"><h2>球队球员</h2><Link to="/players">打开球员目录 →</Link></div><div className="directory-list">{players.map((player) => <PlayerLink key={player.id} player={player} />)}</div></section><DataMethodNote /></>;
}

export function TeamAnalysisPage() {
  const data = useData();
  const [params, setParams] = useSearchParams();
  const teamId = params.get('team') ?? data.teams[0]?.id ?? '';
  const team = data.teams.find((item) => item.id === teamId);
  const stats = team ? getTeamStats(data, team.id, { season: data.seasons[0] })[0] : undefined;
  return <><PageHead eyebrow="TEAM ANALYSIS" title="球队攻防" description="查看当前数据集已经发布的球队效率、节奏和基础赛季指标。" /><StatusCard /><section className="directory-toolbar"><label className="field"><span>选择球队</span><select value={teamId} onChange={(event) => { const next = new URLSearchParams(params); next.set('team', event.target.value); setParams(next, { replace: true }); }}>{data.teams.map((item) => <option key={item.id} value={item.id}>{item.abbreviation} · {item.chineseName}</option>)}</select></label></section>{team ? <><div className="metrics-grid"><article className="metric"><span className="metric-label">进攻效率</span><strong>{number(stats?.offensiveRating)}</strong><p>{data.seasons[0]} · 当前数据</p></article><article className="metric"><span className="metric-label">防守效率</span><strong>{number(stats?.defensiveRating)}</strong><p>数值越低通常代表限制得分更好</p></article><article className="metric"><span className="metric-label">节奏</span><strong>{number(stats?.pace)}</strong><p>回合/场 · 当前覆盖赛季</p></article></div><section className="notice-card"><Shield size={18} /><span>球队攻防明细只展示已发布字段；未提供的高级指标不会用估算值填充。</span></section><Link className="card-link" to={`/teams/${team.id}`}>打开 {team.chineseName} 球队详情 →</Link></> : <Empty title="未找到球队" message="请从球队选择器中选择有效球队。" />}</>;
}

export function TeamComparePage() {
  const data = useData();
  const [params, setParams] = useSearchParams();
  const leftId = params.get('left') ?? data.teams[0]?.id ?? '';
  const rightId = params.get('right') ?? data.teams[1]?.id ?? data.teams[0]?.id ?? '';
  const left = data.teams.find((item) => item.id === leftId);
  const right = data.teams.find((item) => item.id === rightId);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next, { replace: true }); };
  const card = (team: typeof left) => { if (!team) return <article className="unavailable-panel"><h2>未选择球队</h2></article>; const stats = getTeamStats(data, team.id, { season: data.seasons[0] })[0]; return <article className="directory-card"><div className="team-mark" aria-hidden="true">{team.abbreviation.slice(0, 2)}</div><h2>{team.chineseName}</h2><p>{team.name} · {data.seasons[0]}</p><dl><div><dt>进攻效率</dt><dd>{number(stats?.offensiveRating)}</dd></div><div><dt>防守效率</dt><dd>{number(stats?.defensiveRating)}</dd></div><div><dt>节奏</dt><dd>{number(stats?.pace)}</dd></div></dl><Link className="card-link" to={`/teams/${team.id}`}>查看详情 →</Link></article>; };
  return <><PageHead eyebrow="TEAM COMPARISON" title="球队对比" description="并排查看两支 NBA 球队的已发布赛季效率指标；空值保持为 —。" /><StatusCard /><section className="directory-toolbar"><label className="field"><span>左侧球队</span><select value={leftId} onChange={(event) => update('left', event.target.value)}>{data.teams.map((item) => <option key={item.id} value={item.id}>{item.abbreviation} · {item.chineseName}</option>)}</select></label><label className="field"><span>右侧球队</span><select value={rightId} onChange={(event) => update('right', event.target.value)}>{data.teams.map((item) => <option key={item.id} value={item.id}>{item.abbreviation} · {item.chineseName}</option>)}</select></label></section><div className="directory-grid team-directory">{card(left)}{card(right)}</div><DataMethodNote /></>;
}

export function SalariesPage() { return <><PageHead eyebrow="SALARY VAULT" title="薪金仓库" description="薪资数据需要可靠、可追溯的公开来源；当前数据目录未发布薪资字段。" /><StatusCard /><section className="unavailable-panel"><WalletCards size={30} /><h2>Salary data is not available in the current dataset.</h2><p>当前页面不会使用假数据填充薪资、合同年限或球队工资总额。</p><dl><div><dt>预计接入字段</dt><dd>球员薪资、合同年限、合同总额、合同状态</dd></div><div><dt>发布条件</dt><dd>来源可追溯、字段校验通过，并在 manifest 中明确标记可用。</dd></div></dl></section></>; }

export function FuturePage() { return <><PageHead eyebrow="PRODUCT ROADMAP" title="未来展望" description="CourtMatch 的公开产品路线图：只标记已完成、开发中和计划中的功能。" /><section className="roadmap-grid">{[['已完成','NBA-only 数据边界、GitHub JSON 发布层、对位筛选、排行榜、双人比较、抽屉导航'],['正在开发','官方球员目录 ID 映射、生产数据管线、数据质量报告'],['计划开发','历史赛季扩展、更多球队画像、可审计的每日摘要'],['明确边界','WNBA 暂不支持；预测模型不会在可靠数据和验证方案完成前上线']].map(([title, copy], i) => <article className="roadmap-card" key={title}><span>0{i + 1}</span><Rocket size={18} /><h2>{title}</h2><p>{copy}</p></article>)}</section><DataMethodNote /></>; }

export function ImpactPage() { const data = useData(); const rankings = getRankings(data, { season: data.seasons[0], type: 'regular', minPossessions: 25, metric: 'edge', order: 'desc' }).slice(0, 12); return <><PageHead eyebrow="OFFENSE × DEFENSE" title="攻防影响" description="用当前数据集中的对位效率、对位回合和联盟基准观察攻防影响；不把结果解释为因果评分。" /><StatusCard /><DataMethodNote /><section className="section"><div className="section-title"><h2>当前覆盖范围的攻防影响</h2><span>{rankings.length} 位达到最低样本门槛的球员</span></div><div className="impact-list">{rankings.map((r) => <article key={r.player.id}><PlayerLink player={r.player} /><span><b>{number(r.offense)}</b><small>进攻 /100</small></span><span><b>{number(r.defense)}</b><small>被攻 /100</small></span><span className={r.edge && r.edge >= 0 ? 'positive' : 'negative'}><b>{r.edge == null ? '—' : `${r.edge >= 0 ? '+' : ''}${number(r.edge)}`}</b><small>防守压制</small></span></article>)}</div></section></>; }

export function DailyPage() { const data = useData(); const ranking = getRankings(data, { season: data.seasons[0], type: 'regular', minPossessions: 25, metric: 'offense', order: 'desc' }).slice(0, 5); return <><PageHead eyebrow="DAILY BRIEF" title="每日最佳" description="当日摘要优先读取生产数据；当前若未发布逐场日志，会明确显示最近一次可用数据。" /><StatusCard label="每日数据状态" /><section className="notice-card"><CalendarDays size={18} /><span>当前页面使用最近一次可用数据；逐场日志字段将在 daily_player_log 数据接入后启用。</span></section><section className="section"><div className="section-title"><h2>当前可用的对位亮点</h2><span>{data.seasons[0]} · 最近发布数据</span></div><div className="daily-grid">{ranking.map((r) => <article className="directory-card" key={r.player.id}><PlayerIdentity player={r.player} /><strong>{number(r.offense)} <small>/100</small></strong><p>{number(r.offensePossessions, 0)} 个进攻对位回合 · {r.quality.toUpperCase()} 样本</p><Link to={`/players/${r.player.id}`}>查看球员详情 →</Link></article>)}</div></section><DataMethodNote /></>; }

export function CountriesPage() { const data = useData(); const countries = [{ name: 'Unknown / 未知', count: data.players.length, players: data.players }]; return <><PageHead eyebrow="PLAYER ORIGINS" title="球员国家" description="国家字段只有在可靠球员目录映射后才会发布；当前目录尚未提供可验证国家字段。" /><StatusCard /><section className="unavailable-panel"><Globe2 size={30} /><h2>当前球员国家字段不可用</h2><p>不根据姓名、球队或其他线索猜测国家。未映射球员统一保留为 Unknown。</p><div className="country-summary"><strong>{countries[0].count}</strong><span>名球员待映射</span></div></section><section className="section"><div className="section-title"><h2>未映射报告</h2><Link to="/players">查看球员目录 →</Link></div><div className="directory-list">{countries[0].players.slice(0, 8).map((p) => <PlayerLink key={p.id} player={p} />)}</div></section></>; }

export function ChangelogPage() { const data = useData(); const status = useDataStatus(); return <><PageHead eyebrow="RELEASE LOG" title="更新日志" description="版本、数据计数和发布状态来自当前数据 manifest；失败更新不会覆盖上一份有效发布。" /><StatusCard label="发布状态" /><section className="timeline"><article><History size={20} /><div><strong>{status.version}</strong><span>{status.lastUpdated}</span><p>{data.players.length} 位球员 · {data.teams.length} 支球队 · {data.matchups.length.toLocaleString()} 条对位记录 · {data.playtypes.length.toLocaleString()} 条打法记录</p><small>来源：{data.source}。GitHub Actions 数据更新失败时保留旧数据并标记状态。</small></div><CheckCircle2 className="timeline-check" size={18} /></article></section><DataMethodNote /></>; }

export function PlayerDetailRoute() { return null; }
