import { Link } from 'react-router-dom';
import { ArrowUpRight, Search, ArrowRight } from 'lucide-react';
import { Button } from '../components/ui/button';
import { useData } from '../state';
import { getRankings, getMatchups, getPlayerById, calculateMatchupMetrics, leagueAverage } from '../lib/api';
import { PlayerIdentity, Quality, number, signed, PlayerLink, Empty } from '../components/Common';
import { Chart, rankingOption } from '../components/Charts';
export function HomePage({onSearch}:{onSearch:()=>void}){
 const data=useData();const season=data.seasons[0];const ranks=getRankings(data,{season,type:'regular',metric:'offense',order:'desc',minPossessions:25});const featured=getMatchups(data,{season,type:'regular',minPossessions:75}).sort((a,b)=>b.matchupPossessions-a.matchupPossessions).slice(0,3);const focus=featured[0];const a=focus&&getPlayerById(data,focus.offensivePlayerId),b=focus&&getPlayerById(data,focus.defensivePlayerId);const average=leagueAverage(data,{season,type:'regular'});
 return <><section className="hero"><div className="hero-copy"><p className="eyebrow">BASKETBALL, UNDER THE SURFACE.</p><h1>读懂每一次<br/><em>正面对位。</em></h1><p>用直接对位数据，看清谁在攻防回合中真正占据上风。</p><Button variant="default" className="hero-search" onClick={onSearch}><Search size={19}/><span>搜索球员，开始探索<small>Search a player</small></span><kbd>⌘ K</kbd><ArrowRight size={20}/></Button><Link className="text-link" to="/comparison">比较两名球员 <ArrowUpRight size={17}/></Link></div><div className="hero-board">{focus&&a&&b?<><div className="board-top"><span>FEATURED DIRECT MATCHUP</span><span>{season}</span></div><div className="hero-players"><div><span className="jersey">{a.jerseyNumber}</span><PlayerIdentity player={a} large/></div><span className="versus">VS</span><div><span className="jersey">{b.jerseyNumber}</span><PlayerIdentity player={b} large/></div></div><div className="board-score"><div><strong>{number(calculateMatchupMetrics(focus).pointsPer100)}</strong><span>进攻方每 100 对位回合得分</span></div><Quality quality="high" possessions={focus.matchupPossessions}/></div><Link to={`/matchups/player/${a.id}?opponent=${b.id}&season=${season}&minPossessions=0`} className="board-link">进入这组对位 <ArrowUpRight size={20}/></Link></>:<Empty title="暂无精选对位"/>}</div></section>
 <div className="brand-ribbon"><strong>THE GAME WITHIN THE GAME</strong><span>球员 → 视角 → 样本 → 对位</span><Link to="/matchups">打开分析工作台 <ArrowUpRight size={18}/></Link></div>
 <section className="section"><div className="section-title"><div><h2>每一组对位，都有细节。</h2><p>从样本量充足的记录切入，再看效率差异。</p></div><Link className="text-link" to="/matchups">全部对位 <ArrowRight size={17}/></Link></div><div className="matchup-highlights">{featured.map((r,i)=>{const offense=getPlayerById(data,r.offensivePlayerId)!,defense=getPlayerById(data,r.defensivePlayerId)!;const m=calculateMatchupMetrics(r,average);return <article key={r.id} className="highlight"><div className="highlight-top"><span>精选对位 {String(i+1).padStart(2,'0')}</span><Quality quality={m.sampleQuality} possessions={r.matchupPossessions}/></div><PlayerLink player={offense}/><span className="versus-small">进攻面对</span><PlayerLink player={defense}/><div className="highlight-metric"><strong>{number(m.pointsPer100)}</strong><span>每 100 回合得分<br/>{signed(m.differenceFromLeagueAverage)}% 相对数据集均值</span></div><Button asChild><Link to={`/matchups/player/${offense.id}?opponent=${defense.id}&season=${season}&minPossessions=0`}>查看对位详情 <ArrowUpRight size={17}/></Link></Button></article>;})}</div></section>
 <section className="section home-rank"><div><p className="eyebrow">LEAGUE LEADERS</p><h2>让表现<br/>进入视野。</h2><p>基于同一赛季、同一口径的对位回合加权汇总。</p><div className="leader-summary">{[{label:'进攻效率领先',metric:'offense',order:'desc'},{label:'防守限制领先',metric:'defense',order:'asc'},{label:'对位回合领先',metric:'possessions',order:'desc'},{label:'效率提升领先',metric:'improvement',order:'desc'},{label:'效率下降最多',metric:'improvement',order:'asc'}].map(({label,metric,order})=>{const leader=getRankings(data,{season,type:'regular',metric,order:order as 'asc'|'desc',minPossessions:25})[0];return <div key={label}><span>{label}</span>{leader?<Link to={`/players/${leader.player.id}?season=${season}`}>{leader.player.shortName}<ArrowUpRight size={13}/></Link>:<span>暂无数据</span>}</div>;})}</div><Button asChild><Link to="/rankings">进入排行榜 <ArrowRight size={17}/></Link></Button></div><Chart title="进攻对位效率 · 前 8 位" description="橙色条长表示每 100 个直接对位回合得分；数字同样表达大小。点击球员打开画像。" option={rankingOption(ranks.slice(0,8).map(r=>({id:r.player.id,name:r.player.shortName,value:r.offense??0})))} onClick={id=>{window.location.href=`${import.meta.env.BASE_URL}players/${id}`;}}/></section>
 <section className="method-teaser"><h2>数字需要上下文。</h2><p>每一项效率都附带样本回合和比较基准。样本多不代表因果关系，了解算法后再做判断。</p><Link className="text-link" to="/methodology">阅读方法论 <ArrowUpRight size={18}/></Link></section></>;
}
