import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowDownUp } from 'lucide-react';
import { useData, useFilters } from '../state';
import { DEFAULT_FILTERS } from '../lib/filters';
import { aggregateRecords, calculateMatchupMetrics, getPlayerById, getPlayerMatchups, getRankings, leagueAverage } from '../lib/api';
import type { MatchupRecord } from '../lib/types';
import { Chart, scatterOption } from '../components/Charts';
import { Actions, Empty, Field, FilterPanel, Metric, PageHead, Pagination, PlayerIdentity, PlayerLink, Quality, SampleNote, number, signed } from '../components/Common';
import { Button } from '../components/ui/button';
import { ProgressHourglass } from '../components/ProgressHourglass';

const columnNames=['对手','球队','位置','回合','得分','FGA','FGM','FG%','3PA','3P%','FTA','失误','每100回合得分','较均值 %','样本质量'];
export function MatchupsPage({detail=false}:{detail?:boolean}){
 const data=useData();const {filters,update,params}=useFilters();const {playerId}=useParams();const navigate=useNavigate();const current={...filters,player:detail?playerId??filters.player:filters.player};const player=getPlayerById(data,current.player);const opponent=params.get('opponent');const [selected,setSelected]=useState<string[]>([]);const [hidden,setHidden]=useState<string[]>([]);const [chartReady,setChartReady]=useState(false);
 const records=getPlayerMatchups(data,current.player,current).filter(r=>!detail||!opponent||(current.perspective==='offense'?r.defensivePlayerId:r.offensivePlayerId)===opponent);const average=leagueAverage(data,current);const all=aggregateRecords(records);const metrics=all?calculateMatchupMetrics(all,average):null;const rank=getRankings(data,{season:current.season,type:current.type,metric:current.perspective==='defense'?'defense':'offense',order:current.perspective==='defense'?'asc':'desc',minPossessions:0}).find(r=>r.player.id===current.player);
 const opposite=(r:MatchupRecord)=>getPlayerById(data,current.perspective==='defense'?r.offensivePlayerId:r.defensivePlayerId)!;
 const sorted=[...records].filter(r=>!selected.length||selected.includes(r.id)).sort((a,b)=>{const v=(r:MatchupRecord)=>current.metric==='possessions'?r.matchupPossessions:current.metric==='points'?r.points:calculateMatchupMetrics(r).pointsPer100??-Infinity;return(v(a)-v(b))*(current.order==='asc'?1:-1);});const page=Math.min(current.page,Math.max(1,Math.ceil(sorted.length/10)));const slice=sorted.slice((page-1)*10,page*10);useEffect(()=>setChartReady(false),[current.season,current.type,current.perspective,current.team,current.opponentTeam,current.position,current.minPossessions,current.quality,current.search,current.player]);
 const reset=()=>{setSelected([]);update({...DEFAULT_FILTERS,player:playerId??DEFAULT_FILTERS.player});};
 const rows=sorted.map(r=>{const p=opposite(r),m=calculateMatchupMetrics(r,average);return [p.name,p.teamAbbreviation,p.position,r.matchupPossessions,r.points,r.fieldGoalAttempts,r.fieldGoalsMade,m.fieldGoalPercentage,r.threePointAttempts,m.threePointPercentage,r.freeThrowAttempts,r.turnovers,m.pointsPer100,m.differenceFromLeagueAverage,m.sampleQuality];});
 const toDetail=(r:MatchupRecord)=>`/matchups/player/${current.player}?${new URLSearchParams({...Object.fromEntries(params),opponent:opposite(r).id,player:current.player}).toString()}`;
 if(!player)return <Empty title="未找到这位球员" message="链接中的球员 ID 不在当前数据源中。"><Button asChild><Link to="/matchups">返回联盟对位</Link></Button></Empty>;
 return <><PageHead eyebrow={detail?'DIRECT MATCHUP':'MATCHUP EXPLORER'} title={detail?'球员对位详情':'联盟对位'} description="选择球员与视角，让图表和表格一起回答你的问题。"/><FilterPanel filters={current} onChange={patch=>{setSelected([]);if(detail&&patch.player)navigate(`/matchups?${new URLSearchParams({...Object.fromEntries(params),player:patch.player}).toString()}`);else update(patch);}} onReset={reset}><Field label="搜索对手"><input value={current.search} onChange={e=>update({search:e.target.value})} placeholder="姓名 / 球队 / 中文"/></Field></FilterPanel><ProgressHourglass activeLabel={chartReady?'筛选、指标和图表均已就绪':records.length?'正在完成交互图表渲染':'正在检查当前筛选结果'} stages={[{id:'filters',label:'读取筛选条件',complete:true,weight:20},{id:'player',label:'定位球员档案',complete:!!player,weight:20},{id:'records',label:'聚合对位记录',complete:records.length>0,weight:20},{id:'metrics',label:'计算核心指标',complete:!!metrics,weight:20},{id:'chart',label:'绘制交互图表',complete:chartReady,weight:20}]}/>
 <section className="player-banner"><PlayerIdentity player={player} large/><div className="player-facts"><span>{player.height} / #{player.jerseyNumber}</span><span>{current.season} {current.type==='regular'?'常规赛':'季后赛'}</span><Link to={`/players/${player.id}?season=${current.season}&type=${current.type}`}>打开完整球员画像 ↗</Link></div></section>
 <div className="metrics-grid"><Metric label="对位总回合" value={all?number(all.matchupPossessions,0):'—'} basis={`${records.length} 条筛选后记录`} help="所有符合筛选条件的追踪对位回合之和。"/><Metric label={current.perspective==='offense'?'进攻对位效率':'被攻对位效率'} value={number(metrics?.pointsPer100)} unit="/100" basis={all?`${all.matchupPossessions} 对位回合`:'无符合条件的样本'} delta={metrics?.pointsPer100!=null&&average!=null?metrics.pointsPer100-average:null} help="100 × 得分 ÷ 追踪对位回合数。防守视角数值越低通常表示限制越强。"/><Metric label="数据集内排名" value={rank?`#${rank.rank}`:'—'} basis="同赛季 / 比赛类型全量汇总" help="排名使用全赛季球员汇总，不随对手或单条记录筛选变化。"/><Metric label="数据集平均" value={number(average)} unit="/100" basis="全部覆盖球员的回合加权值" help="这是当前数据集均值；演示或局部数据不能代表官方全联盟均值。"/><Metric label="相对均值" value={signed(metrics?.differenceFromLeagueAverage)} unit="%" basis={all?`基于 ${all.matchupPossessions} 回合`:'无样本'} help="(所选效率 / 数据集平均 - 1) × 100%。"/><Metric label="样本等级" value={metrics?.sampleQuality.toUpperCase()??'—'} basis={all?`${all.matchupPossessions} 汇总回合`:'无样本'} help="Low <25，Medium 25-74，High ≥75；仅按样本大小分级。"/></div>
 <Actions title={`${player.name} 对位分析`} subtitle={`${current.season} / ${current.perspective==='offense'?'进攻':'防守'}`} headers={columnNames} rows={rows} metrics={[{label:'每100回合得分',value:number(metrics?.pointsPer100)},{label:'回合',value:all?number(all.matchupPossessions,0):'—'},{label:'相对均值',value:`${signed(metrics?.differenceFromLeagueAverage)}%`}]} players={[player]}/>
 {records.length?<><Chart onReady={()=>setChartReady(true)} title="对位分布" description="横轴：对位回合数；纵轴：每100回合得分；圆点大小代表得分。悬停查看数据，点击数据点进入该对手详情。" option={scatterOption(records.flatMap(r=>{const m=calculateMatchupMetrics(r);return m.pointsPer100==null?[]:[{id:r.id,name:opposite(r).name,possessions:r.matchupPossessions,efficiency:m.pointsPer100,points:r.points}];}),average??0,current.minPossessions)} onSelect={setSelected} onClick={id=>{const r=records.find(r=>r.id===id);if(r)navigate(toDetail(r));}}/><SampleNote records={records}/></>:<Empty><Button onClick={reset}>清除筛选</Button></Empty>}
 <section className="section table-section"><div className="section-title"><h2>对位记录</h2><div className="actions">{selected.length>0&&<Button onClick={()=>setSelected([])}>取消框选 ({selected.length})</Button>}<details className="column-menu"><summary>显示列</summary><div>{columnNames.slice(1).map(c=><label key={c}><input type="checkbox" checked={!hidden.includes(c)} onChange={()=>setHidden(h=>h.includes(c)?h.filter(v=>v!==c):[...h,c])}/>{c}</label>)}</div></details><Field label="排序指标"><select value={['possessions','points'].includes(current.metric)?current.metric:'efficiency'} onChange={e=>update({metric:e.target.value})}><option value="efficiency">每100回合得分</option><option value="possessions">对位回合</option><option value="points">得分</option></select></Field><Button aria-label="切换排序方向" onClick={()=>update({order:current.order==='desc'?'asc':'desc'})}><ArrowDownUp size={17}/>{current.order==='desc'?'降序':'升序'}</Button></div></div><div className="table-scroll"><table><caption className="sr-only">{player.name} 对位记录，点击对手查看详情</caption><thead><tr><th scope="col">序号</th>{columnNames.filter(c=>!hidden.includes(c)).map(c=><th scope="col" key={c}>{c}</th>)}</tr></thead><tbody>{slice.map((r,i)=>{const p=opposite(r),m=calculateMatchupMetrics(r,average);const values=[p.teamAbbreviation,p.position,number(r.matchupPossessions,0),number(r.points,0),r.fieldGoalAttempts,r.fieldGoalsMade,number(m.fieldGoalPercentage)+'%',r.threePointAttempts,number(m.threePointPercentage)+'%',r.freeThrowAttempts,r.turnovers,number(m.pointsPer100),signed(m.differenceFromLeagueAverage),<Quality key="q" quality={m.sampleQuality} possessions={r.matchupPossessions}/>];return <tr key={r.id}><td>{(page-1)*10+i+1}</td><td><PlayerLink player={p} to={toDetail(r)}/></td>{values.map((v,j)=>hidden.includes(columnNames[j+1])?null:<td key={columnNames[j+1]}>{v}</td>)}</tr>;})}</tbody></table></div>{!sorted.length&&<Empty title="没有可显示的记录"/>}<Pagination page={page} total={sorted.length} onChange={p=>update({page:p},false)}/></section>
 {detail&&all&&<section className="analysis-note"><h2>如何阅读这组对位</h2><p>{player.chineseName}{current.perspective==='offense'?'进攻':'防守'}视角的结果基于 {all.matchupPossessions} 回合，每 100 回合{current.perspective==='offense'?'得到':'让对手得到'} {number(metrics?.pointsPer100)} 分，比数据集均值{(metrics?.differenceFromLeagueAverage??0)>=0?'高':'低'} {number(Math.abs(metrics?.differenceFromLeagueAverage??0))}%。这描述的是这些样本中的表现，不证明球员能力或单个防守者造成了差异。</p><p>估算进攻机会效率：{number(metrics?.efficiency,3)} 分/次，使用 PTS ÷ (FGA + 0.44 × FTA + TOV)。</p>{opponent&&<Button asChild><Link to={`/comparison?a=${player.id}&b=${opponent}&season=${current.season}&type=${current.type}&minPossessions=${current.minPossessions}`}>比较双方互相防守</Link></Button>}</section>}</>;
}
