import { Link, useParams } from 'react-router-dom';
import { useData, useFilters } from '../state';
import { aggregateRecords, calculateMatchupMetrics, getPlayerById, getPlayerMatchups, leagueAverage } from '../lib/api';
import { Chart, heatmapOption, lineOption, radarOption } from '../components/Charts';
import { Actions, DataMethodNote, Empty, Metric, PageHead, PlayerIdentity, PlayerLink, number } from '../components/Common';
import { Button } from '../components/ui/button';
import { useLanguage } from '../i18n';

export function PlayerPage(){
 const data=useData();const {playerId}=useParams();const {filters}=useFilters();const {language}=useLanguage();const en=language==='en';
 const player=playerId?getPlayerById(data,playerId):undefined;
 if(!player)return <Empty title={en?'Player not found':'未找到这位球员'} message={en?'Choose a player from Matchups or global search.':'请从联盟对位或全局搜索选择球员。'}><Button asChild><Link to="/matchups">{en?'Go to Matchups':'去联盟对位'}</Link></Button></Empty>;
 const offense=getPlayerMatchups(data,player.id,{...filters,perspective:'offense'}),defense=getPlayerMatchups(data,player.id,{...filters,perspective:'defense'});const o=aggregateRecords(offense),d=aggregateRecords(defense),avg=leagueAverage(data,filters),om=o?calculateMatchupMetrics(o,avg):null,dm=d?calculateMatchupMetrics(d,avg):null;
 const trend=data.seasons.map(season=>{const r=aggregateRecords(getPlayerMatchups(data,player.id,{...filters,season,perspective:'offense'}));return {label:season,value:r?calculateMatchupMetrics(r).pointsPer100:null};});
 const opponents=offense.slice().sort((a,b)=>b.matchupPossessions-a.matchupPossessions).slice(0,5).map(r=>({x:getPlayerById(data,r.defensivePlayerId)?.shortName??'—',y:en?'Offense':'进攻',value:calculateMatchupMetrics(r).pointsPer100??0}));
 const radar=[om?.pointsPer100??0,100-(dm?.pointsPer100??100),Math.min(100,(o?.matchupPossessions??0)/4),100-(om?.turnoverRate??100)*3,om?.fieldGoalPercentage??0].map(v=>Math.max(0,Math.min(100,v)));
 const type=filters.type==='regular'?(en?'regular season':'常规赛'):(en?'playoffs':'季后赛');
 return <><PageHead eyebrow="PLAYER PROFILE" title={`${player.chineseName} · ${player.name}`} description={en?`${player.teamName} / ${player.position}. Offense, defense, trends and frequent opponents in one view.`:`${player.teamName} / ${player.position}。同一页面汇总进攻、被攻、趋势与常见对手。`}/><DataMethodNote/>
  <section className="profile-hero"><PlayerIdentity player={player} large/><div><span>{player.height} · {player.weight} lb · #{player.jerseyNumber}</span><p>{en?`Current filters: ${filters.season} ${type}. Metrics use the explicitly labeled dataset.`:`当前筛选：${filters.season} ${type}。所有指标来自明确标注的数据集。`}</p><Button asChild><Link to={`/matchups/player/${player.id}?season=${filters.season}&type=${filters.type}`}>{en?'Open full matchup log':'打开完整对位记录'}</Link></Button></div></section>
  <div className="metrics-grid"><Metric label={en?'Offensive matchup efficiency':'进攻对位效率'} value={number(om?.pointsPer100)} unit="/100" basis={`${o?.matchupPossessions??0} ${en?'possessions':'回合'}`} help={en?'Player scoring as the offensive player, per 100 tracked matchup possessions.':'该球员作为进攻方时，100 × 得分 ÷ 对位回合。'}/><Metric label={en?'Opponent efficiency allowed':'被攻对位效率'} value={number(dm?.pointsPer100)} unit="/100" basis={`${d?.matchupPossessions??0} ${en?'possessions':'回合'}`} help={en?'Opponent points per 100 matchup possessions; lower is generally better.':'该球员作为防守方时，对手的每100对位回合得分；更低通常更好。'}/><Metric label={en?'Offensive sample':'进攻样本'} value={o?number(o.matchupPossessions,0):'—'} basis={om?`${om.sampleQuality.toUpperCase()} ${en?'sample tier':'样本等级'}`:(en?'No sample':'暂无样本')} help={en?'Used only to describe sample size.':'仅用于样本量提示。'}/><Metric label={en?'Dataset average':'数据集平均'} value={number(avg)} unit="/100" basis={en?'Possession-weighted average in current coverage':'回合加权的当前数据集平均'} help={en?'Not a full official league average.':'不是官方全联盟均值。'}/></div>
  <div className="chart-grid"><Chart title={en?'Season efficiency trend':'赛季效率趋势'} description={en?'Points per 100 matchup possessions by season type. Missing values are not connected.':'按当前比赛类型汇总的每100对位回合得分。缺失值不会被连线。'} option={lineOption(trend,en?'Offensive efficiency':'进攻效率')}/><Chart title={en?'Offense & defense profile':'攻防轮廓'} description={en?'Normalized view, not an official composite rating or player ranking.':'归一化展示：不是官方综合评分，也不应用于球员排名。'} option={radarOption(en?['Offensive output','Opponent restriction','Sample coverage','Turnover control','Shooting']:['进攻产出','限制对手','样本覆盖','失误控制','投篮命中'],radar,player.shortName)}/></div>
  <Chart title={en?'Frequent-opponent heatmap':'常见对手热力图'} description={en?'Opponents and points per 100 matchup possessions for the five most frequent opponents in the current filters.':'横向为对手，色深与格内数字均为每100对位回合得分；仅显示当前筛选下前五个对手。'} option={heatmapOption(opponents.length?opponents:[{x:en?'No data':'暂无',y:en?'Offense':'进攻',value:0}])} height={280}/>
  <section className="section"><div className="section-title"><h2>{en?'Most frequent opponents':'最常遇到的对手'}</h2><Link to={`/matchups/player/${player.id}`}>{en?'View all records →':'查看全部记录 →'}</Link></div><div className="opponent-list">{offense.slice().sort((a,b)=>b.matchupPossessions-a.matchupPossessions).slice(0,5).map(r=>{const p=getPlayerById(data,r.defensivePlayerId)!;const m=calculateMatchupMetrics(r,avg);return <article key={r.id}><PlayerLink player={p} to={`/matchups/player/${player.id}?opponent=${p.id}`}/><span>{number(m.pointsPer100)} /100</span><small>{m.sampleQuality.toUpperCase()} · {r.matchupPossessions} {en?'possessions':'回合'}</small></article>;})}</div></section>
  <Actions title={`${player.name} ${en?'Player Profile':'球员画像'}`} subtitle={`${filters.season} / ${type}`} metrics={[{label:en?'Offense /100':'进攻 /100',value:number(om?.pointsPer100)},{label:en?'Allowed /100':'被攻 /100',value:number(dm?.pointsPer100)},{label:en?'Offensive possessions':'进攻回合',value:number(o?.matchupPossessions,0)}]} players={[player]}/>
 </>;
}
