import { Fragment, useEffect, useMemo, useRef, useState } from 'react';
import { useData, useDataStatus, useFilters } from '../state';
import { DEFAULT_FILTERS } from '../lib/filters';
import { getRankings } from '../lib/api';
import { Actions, DataMethodNote, Field, FilterPanel, PageHead, PlayerLink, Quality, number, signed } from '../components/Common';
import { Button } from '../components/ui/button';
import { useLanguage } from '../i18n';
import './rankings.css';

const options=[['offense','Highest offensive matchup efficiency','最高进攻对位效率'],['defense','Lowest opponent efficiency allowed','最低被防效率'],['possessions','Most matchup possessions','最多对位回合'],['edge','Strongest defensive restriction','最强防守压制'],['improvement','Largest efficiency improvement','最大效率提升'],['decline','Largest efficiency decline','最大效率下降'],['stability','Most consistent players','最稳定球员']] as const;

export function RankingsPage(){
 const data=useData();const status=useDataStatus();const {language}=useLanguage();const en=language==='en';const {filters,params,update}=useFilters();const [expanded,setExpanded]=useState<string>('');const [visibleCount,setVisibleCount]=useState(30);const loadMoreRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const patch:{minPossessions?:number;page?:number}={};if(!params.has('minPossessions'))patch.minPossessions=50;if(params.has('page'))patch.page=1;if(Object.keys(patch).length)update(patch,false);},[params,update]);
 useEffect(()=>{setVisibleCount(30);setExpanded('');},[filters.search,filters.season,filters.type,filters.metric,filters.order,filters.minPossessions,filters.team]);
 const rows=useMemo(()=>getRankings(data,filters),[data,filters]);const slice=rows.slice(0,visibleCount);
 useEffect(()=>{const node=loadMoreRef.current;if(!node||slice.length>=rows.length)return;if(!('IntersectionObserver'in window)){setVisibleCount(rows.length);return;}const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))setVisibleCount(current=>Math.min(current+30,rows.length));},{rootMargin:'320px 0px'});observer.observe(node);return()=>observer.disconnect();},[rows.length,slice.length]);
 const selected=options.find(x=>x[0]===filters.metric);const title=selected?(en?selected[1]:selected[2]):(en?'League rankings':'联盟排行榜');const reset=()=>update({...DEFAULT_FILTERS,player:'',metric:'offense',minPossessions:50});
 const currentMetric=(r:typeof rows[number])=>filters.metric==='defense'?r.defense:filters.metric==='possessions'?r.possessions:filters.metric==='edge'?r.edge:filters.metric==='stability'?r.stability:r.offense;
 const typeLabel=filters.type==='regular'?(en?'Regular season':'常规赛'):(en?'Playoffs':'季后赛');
 return <><PageHead eyebrow="LEAGUE LEADERS" title={en?'Rankings':'排行榜'} description={en?'Rankings include players who meet the selected matchup-sample threshold.':'排行榜仅纳入达到所选对位样本门槛的球员。'}/><DataMethodNote/>
  <section className="ranking-status"><span>{status.state==='live'?(en?'LIVE DATA':'实时数据'):status.state==='recently-updated'?(en?'RECENTLY UPDATED':'最近更新'):(en?'DEMO DATA':'演示数据')}</span><b>{en?`Qualified players: ${rows.length}`:`合格球员：${rows.length}`}</b><b>{en?`Minimum sample: ${filters.minPossessions} possessions`:`最低样本：${filters.minPossessions} 回合`}</b><small>{en?'Updated':'更新'} {status.lastUpdated.slice(0,10)} · {status.coverage}</small></section>
  <FilterPanel rankings filters={filters} onChange={update} onReset={reset}><Field label={en?'Search players / teams':'搜索球员 / 球队'}><input value={filters.search} placeholder={en?'e.g. Curry / GSW':'例如 Curry / GSW'} onChange={e=>update({search:e.target.value})}/></Field><label className="field"><span>{en?'Ranking metric':'榜单类别'}</span><select value={filters.metric} onChange={e=>update({metric:e.target.value})}>{options.map(([v,english,chinese])=><option key={v} value={v}>{en?english:chinese}</option>)}</select></label></FilterPanel>
  <section className="section table-section"><div className="section-title"><div><h2>{title}</h2><p className="sample-note">{en?'The default 50-possession threshold keeps low-sample players from leading. If you lower it, low-sample warnings remain visible.':'默认 50 回合门槛可避免低样本球员领先；如手动调低门槛，仍会显示小样本提示。'}</p></div><Button onClick={()=>update({order:filters.order==='desc'?'asc':'desc'})}>{en?(filters.order==='desc'?'Sort: descending':'Sort: ascending'):(filters.order==='desc'?'当前：降序':'当前：升序')}</Button></div>
   <div className="table-scroll"><table><caption className="sr-only">{title}</caption><thead><tr>{(en?['Rank','Player','Team','Position','Offense /100','Allowed /100','Possessions','vs average','Selected metric','Sample','Updated']:['排名','球员','球队','位置','进攻 /100','被攻 /100','对位回合','相对均值','当前指标','样本','更新']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{slice.map(r=><Fragment key={r.player.id}><tr className={expanded===r.player.id?'expanded':''} onClick={()=>setExpanded(expanded===r.player.id?'':r.player.id)}><td>#{r.rank}<small>{en?'Position':'位置'} #{r.positionRank}</small></td><td><PlayerLink player={r.player}/></td><td>{r.player.teamAbbreviation}</td><td>{r.player.position}</td><td>{number(r.offense)}</td><td>{number(r.defense)}</td><td>{number(r.possessions,0)}</td><td>{signed(r.improvement)}%</td><td>{number(currentMetric(r))}</td><td><Quality quality={r.quality} possessions={r.possessions}/>{r.possessions<50&&<small className="low-sample">{en?'Small sample · Interpret with caution':'小样本 · 请谨慎解读'}</small>}</td><td>{status.lastUpdated.slice(0,10)}</td></tr>{expanded===r.player.id&&<tr className="ranking-detail"><td colSpan={11}>{en?`Position rank #${r.positionRank} · Defensive restriction ${number(r.edge)} /100 · Stability ${number(r.stability)} · Descriptive only; not a causal conclusion.`:`同位置排名 #${r.positionRank} · 防守压制 ${number(r.edge)} /100 · 稳定性 ${number(r.stability)} · 该展开项只描述当前筛选数据，不构成因果结论。`}</td></tr>}</Fragment>)}</tbody></table></div>
   {!rows.length&&<div className="empty"><h3>{en?'No qualified players match these filters':'当前条件下没有合格球员'}</h3><Button onClick={reset}>{en?'Restore default 50-possession threshold':'使用默认 50 回合门槛'}</Button></div>}{slice.length<rows.length&&<div ref={loadMoreRef} className="ranking-scroll-status" role="status" aria-live="polite">{en?`Showing ${slice.length} of ${rows.length} players · Scroll to load more`:`已显示 ${slice.length} / ${rows.length} 名球员 · 继续向下滚动加载`}</div>}{rows.length>0&&slice.length===rows.length&&<div className="ranking-scroll-status" role="status">{en?`All ${rows.length} players are shown`:`已显示全部 ${rows.length} 名球员`}</div>}
  </section><Actions title={title} subtitle={`${filters.season} ${typeLabel} · ${status.state}`} headers={en?['Rank','Player','Team','Offense/100','Allowed/100','Possessions','Change','Sample']:['排名','球员','球队','进攻/100','被攻/100','回合','提升','样本']} rows={rows.map(r=>[r.rank,r.player.name,r.player.teamAbbreviation,r.offense,r.defense,r.possessions,r.improvement,r.quality])} metrics={slice.slice(0,3).map(r=>({label:r.player.shortName,value:number(currentMetric(r))}))}/>
 </>;
}
