/* Chart rows intentionally support several native chart shapes. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect } from 'react';
export type ChartOption={kind:'scatter'|'bar'|'line'|'compare'|'radar'|'heatmap';rows?:any[];labels?:string[];values?:any[];average?:number;min?:number;name?:string};
export function Chart({title,description,option,onClick,onSelect,onReady,height=390}:{title:string;description:string;option:ChartOption;onClick?:(id:string)=>void;onSelect?:(ids:string[])=>void;onReady?:()=>void;height?:number}){useEffect(()=>{const timer=window.setTimeout(()=>onReady?.(),80);return()=>window.clearTimeout(timer);},[onReady,option]);const rows=option.rows??[];return <section className={`chart-panel chart-${option.kind}`}><header><h2>{title}</h2><p>{description}</p></header><div className="chart-canvas native-chart" style={{height}} role="img" aria-label={`${title}。${description}`}>{option.kind==='scatter'&&<div className="scatter-plot">{rows.map((r,i)=><button key={r.id} title={`${r.name}：${r.efficiency.toFixed(1)} /100`} onClick={()=>onClick?.(r.id)} onDoubleClick={()=>onSelect?.([r.id])} style={{left:`${8+(i*31)%84}%`,bottom:`${8+Math.max(0,Math.min(78,(r.efficiency-(option.average??0)+25)*1.55))}%`,width:Math.max(12,Math.min(34,Math.sqrt(r.points)*2))}}><span>{r.name}</span></button>)}<i className="average-line" style={{bottom:'47%'}}/><em>点击圆点打开详情 · 双击选中</em></div>}{option.kind==='bar'&&<div className="bar-chart">{rows.map(r=><div key={r.id}><span>{r.name}</span><i style={{width:`${Math.max(4,Math.min(100,r.value))}%`}}/><b>{Number(r.value).toFixed(1)}</b></div>)}</div>}{option.kind==='line'&&<div className="line-chart">{rows.map((r,i)=><div key={r.label} style={{height:`${Math.max(8,Math.min(88,r.value??0))}%`,left:`${8+i*(82/Math.max(1,rows.length-1))}%`}}><b>{r.label}</b><span>{r.value?.toFixed(1)??'—'}</span></div>)}</div>}{option.kind==='compare'&&<div className="compare-chart">{(option.values??[]).map((v:any,i)=><div key={option.labels?.[i]}><b>{option.labels?.[i]}</b><i style={{height:`${Math.min(100,Number(v[0]??0))}%`}}/><i style={{height:`${Math.min(100,Number(v[1]??0))}%`}}/><small>{v[0]?.toFixed?.(1)??'—'} / {v[1]?.toFixed?.(1)??'—'}</small></div>)}</div>}{option.kind==='radar'&&<div className="radar-chart">{(option.values??[]).map((v:number,i)=><div key={option.labels?.[i]}><span>{option.labels?.[i]}</span><i style={{width:`${v}%`}}/><b>{v.toFixed(0)}</b></div>)}</div>}{option.kind==='heatmap'&&<div className="heatmap-chart">{rows.map(r=><div key={r.x} style={{backgroundColor:`hsl(${18+Math.max(0,Math.min(70,100-r.value))*1.2} 72% ${Math.max(26,Math.min(56,r.value/2))}%)`}}><span>{r.x}</span><b>{r.value.toFixed(0)}</b></div>)}</div>}</div></section>}
export function scatterOption(rows:{id:string;name:string;possessions:number;efficiency:number;points:number}[],average:number,min:number):ChartOption{return {kind:'scatter',rows,average,min};}
export function rankingOption(rows:{id:string;name:string;value:number}[]):ChartOption{return {kind:'bar',rows};}
export function lineOption(rows:{label:string;value:number|null}[],name:string):ChartOption{return {kind:'line',rows,name};}
export function compareOption(labels:string[],a:string,b:string,av:string,values:[number|null,number|null,number|null][]):ChartOption{return {kind:'compare',labels,values,name:`${a} / ${b} / ${av}`};}
export function radarOption(labels:string[],values:number[],name:string):ChartOption{return {kind:'radar',labels,values,name};}
export function heatmapOption(rows:{x:string;y:string;value:number}[]):ChartOption{return {kind:'heatmap',rows};}
