import { useState, type ReactNode } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowDown, ArrowUp, ArrowUpRight, Download, ImageDown, Link2, SlidersHorizontal, HelpCircle } from 'lucide-react';
import { Button } from './ui/button';
import type { Filters, Player, SampleQuality, MatchupRecord } from '../lib/types';
import { useData } from '../state';
import { getPlayers, searchPlayers } from '../lib/api';
import { downloadCSV, copyLink, downloadShareCard } from '../lib/export';

export const number=(v:number|null|undefined,digits=1)=>v==null||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits});
export const signed=(v:number|null|undefined,digits=1)=>v==null?'—':`${v>=0?'+':''}${number(v,digits)}`;
export function Avatar({player,large=false}:{player:Player;large?:boolean}){const [failed,setFailed]=useState(false);return <span className={`avatar ${large?'avatar-large':''}`}><span aria-hidden="true">{player.shortName.split(' ').map(x=>x[0]).join('').slice(0,2)}</span>{!failed&&player.headshotUrl&&<img src={player.headshotUrl} alt={`${player.name} 球员头像`} loading="lazy" onError={()=>setFailed(true)}/>}</span>;}
export function PlayerIdentity({player,large=false}:{player:Player;large?:boolean}){return <div className="player-identity"><Avatar player={player} large={large}/><div><strong>{player.name}</strong><span>{player.chineseName} / {player.teamAbbreviation} / {player.position}</span></div></div>;}
export function Quality({quality,possessions}:{quality:SampleQuality;possessions:number}){return <span className={`quality quality-${quality}`} title="仅按样本回合数量分级，不代表统计置信度">{quality==='high'?'High':quality==='medium'?'Medium':'Low'} · {number(possessions,0)} 回合</span>;}
export function PageHead({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}){return <header className="page-head"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1><p>{description}</p></div>{children}</header>;}
export function Empty({title='没有符合条件的对位',message='尝试降低最低回合数或清除筛选条件。',children}:{title?:string;message?:string;children?:ReactNode}){return <div className="empty"><SlidersHorizontal size={27}/><h3>{title}</h3><p>{message}</p>{children}</div>;}
export function Metric({label,value,unit,basis,help,delta}:{label:string;value:string;unit?:string;basis:string;help:string;delta?:number|null}){return <article className="metric"><div className="metric-label">{label}<span tabIndex={0} className="hint" aria-label={help}><HelpCircle size={13}/><span role="tooltip">{help}</span></span></div><strong>{value}<small>{unit}</small></strong><p>{basis}</p>{delta!=null&&<span className={`delta ${delta>=0?'positive':'negative'}`}>{delta>=0?<ArrowUp size={13}/>:<ArrowDown size={13}/>} {signed(delta)} 对比联盟</span>}</article>;}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export function FilterPanel({filters,onChange,onReset,children,rankings=false}:{filters:Filters;onChange:(patch:Partial<Filters>)=>void;onReset:()=>void;children?:ReactNode;rankings?:boolean}){
 const data=useData();const pool=getPlayers(data).filter(p=>!filters.team||p.teamId===filters.team);const [params,setParams]=useSearchParams();const locked=params.get('lockedOpponent')==='1';const lockedOpponent=params.get('opponent')??'';
 return <details className="filters" open><summary><SlidersHorizontal size={16}/> 筛选条件 <span>调整赛季、视角与样本范围</span></summary><div className="filter-grid">
 <Field label="赛季"><select value={filters.season} onChange={e=>onChange({season:e.target.value})}>{data.seasons.map(s=><option key={s}>{s}</option>)}</select></Field>
 <Field label="比赛类型"><select value={filters.type} onChange={e=>onChange({type:e.target.value as Filters['type']})}><option value="regular">常规赛</option><option value="playoffs">季后赛</option></select></Field>
 <Field label="球队"><select value={filters.team} onChange={e=>{const first=getPlayers(data).find(p=>!e.target.value||p.teamId===e.target.value);onChange({team:e.target.value,...(!rankings&&first?{player:first.id}:{})});}}><option value="">所有球队</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.abbreviation} {t.chineseName}</option>)}</select></Field>
 {!rankings&&<><Field label="球员"><select value={filters.player} onChange={e=>onChange({player:e.target.value})}>{pool.map(p=><option key={p.id} value={p.id}>{p.chineseName} · {p.name}</option>)}</select></Field><Field label="视角"><select value={filters.perspective} onChange={e=>onChange({perspective:e.target.value as Filters['perspective']})}><option value="offense">进攻视角</option><option value="defense">防守视角</option></select></Field><Field label="对手球队"><select value={filters.opponentTeam} onChange={e=>onChange({opponentTeam:e.target.value})}><option value="">所有对手</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.abbreviation} {t.chineseName}</option>)}</select></Field><Field label="锁定对手"><select value={lockedOpponent} onChange={e=>{const next=new URLSearchParams(params);if(e.target.value)next.set('opponent',e.target.value);else{next.delete('opponent');next.delete('lockedOpponent');}setParams(next,{replace:true});}}><option value="">不限球员</option>{data.players.filter(p=>p.id!==filters.player).map(p=><option key={p.id} value={p.id}>{p.name} · {p.teamAbbreviation}</option>)}</select></Field><Button disabled={!lockedOpponent} onClick={()=>{const next=new URLSearchParams(params);if(locked)next.delete('lockedOpponent');else next.set('lockedOpponent','1');setParams(next,{replace:true});}}>{locked?'取消锁定':'锁定对手'}</Button></>}
 <Field label="位置"><select value={filters.position} onChange={e=>onChange({position:e.target.value})}><option value="">全部位置</option>{['G','F','C','G-F','F-C'].map(v=><option key={v}>{v}</option>)}</select></Field>
 <Field label="最少对位回合"><input type="number" inputMode="numeric" min={0} max={500} value={filters.minPossessions} onChange={e=>onChange({minPossessions:Math.min(500,Math.max(0,Number(e.target.value)||0))})}/></Field>
 <Field label="样本质量"><select value={filters.quality} onChange={e=>onChange({quality:e.target.value})}><option value="">全部样本</option><option value="low">Low &lt; 25 回合</option><option value="medium">Medium 25-74 回合</option><option value="high">High ≥ 75 回合</option></select></Field>
 {children}<Button onClick={onReset} className="filter-reset">清除筛选</Button></div></details>;
}
export function SearchPlayers({onChoose,label='搜索球员',team='',autoFocus=false}:{onChoose:(p:Player)=>void;label?:string;team?:string;autoFocus?:boolean}){const data=useData();const [query,setQuery]=useState('');const matches=searchPlayers(data,query,team).slice(0,8);const [index,setIndex]=useState(0);return <div className="player-search"><label className="field"><span>{label}</span><input autoFocus={autoFocus} value={query} placeholder="姓名、中文名、缩写或球队" onChange={e=>{setQuery(e.target.value);setIndex(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,matches.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'&&matches[index]){e.preventDefault();onChoose(matches[index]);}}} aria-controls="player-results" aria-autocomplete="list"/></label><div className="search-results" id="player-results">{matches.length?matches.map((p,i)=><button type="button" className={i===index?'search-result selected':'search-result'} key={p.id} onClick={()=>onChoose(p)}><PlayerIdentity player={p}/><ArrowUpRight size={18}/></button>):<Empty title="未找到球员" message="试试 Curry、库里、GSW 或其他球队名称。"/>}</div></div>;}
export function Actions({title,subtitle='',rows,headers,metrics,players=[]}:{title:string;subtitle?:string;headers?:string[];rows?:(string|number|null)[][];metrics:{label:string;value:string}[];players?:Player[]}){const data=useData();const [status,setStatus]=useState('');return <div className="export-actions"><div className="actions"><Button onClick={async()=>{setStatus(await copyLink()?'链接已复制，可还原当前筛选':`请复制链接：${window.location.href}`);}}><Link2 size={15}/>复制链接</Button>{rows&&headers&&<Button onClick={()=>{downloadCSV('courtmatch.csv',headers,rows);setStatus('CSV 已导出，包含当前全部筛选结果。');}}><Download size={15}/>导出 CSV</Button>}<Button onClick={async()=>{try{await downloadShareCard({title,subtitle,metrics,players,updatedAt:data.updatedAt,mode:data.mode});setStatus('PNG 分享卡片已生成。');}catch{setStatus('图片生成失败，请重试。');}}}><ImageDown size={15}/>导出 PNG</Button></div>{status&&<p className="feedback" role="status">{status}</p>}</div>;}
export function PlayerLink({player,to}:{player:Player;to?:string}){return <Link className="player-link" to={to??`/players/${player.id}`}><PlayerIdentity player={player}/><ArrowUpRight size={15}/></Link>;}
export function Pagination({page,total,pageSize=10,onChange}:{page:number;total:number;pageSize?:number;onChange:(p:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));return <nav className="pagination" aria-label="结果分页"><span>{total} 条结果 · 第 {Math.min(page,pages)} / {pages} 页</span><Button disabled={page<=1} onClick={()=>onChange(page-1)}>上一页</Button><Button disabled={page>=pages} onClick={()=>onChange(page+1)}>下一页</Button></nav>;}
export function SampleNote({records}:{records:MatchupRecord[]}){const low=records.filter(r=>r.matchupPossessions<25).length;return <p className="sample-note">{low>0?`${low} 条结果小于 25 回合。Small sample. Interpret with caution. `:''}样本等级仅表示回合数量；阵容、协防和赛程都会影响结果。</p>;}
