import { useState, type ReactNode, type CSSProperties } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowDown, ArrowUp, ArrowUpRight, Download, ImageDown, Link2, SlidersHorizontal, HelpCircle } from 'lucide-react';
import { Button } from './ui/button';
import type { Filters, Player, SampleQuality, MatchupRecord, AvatarSize } from '../lib/types';
import { normalizePossessions, possessionSteps } from '../lib/filters';
import { useData, useDataStatus } from '../state';
import { getPlayers, searchPlayers } from '../lib/api';
import { downloadCSV, copyLink, downloadShareCard } from '../lib/export';
import { PlayerAvatar } from './PlayerAvatar';
import { useLanguage } from '../i18n';
import { teamOptionLabel } from '../lib/team-display';

export const number=(v:number|null|undefined,digits=1)=>v==null||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits});
export const signed=(v:number|null|undefined,digits=1)=>v==null?'—':`${v>=0?'+':''}${number(v,digits)}`;
export function MetricHeatCell({value, mode, children}:{value:number|null|undefined;mode:'number'|'fill';children:ReactNode}){const intensity=value==null?0:Math.max(0,Math.min(1,Math.abs(value)/60));return <span className={mode==='fill'?'metric-heat-cell':''} style={mode==='fill'?({'--heat':intensity} as CSSProperties):undefined} title={mode==='fill'?'颜色表示相对效率强度；数字仍为实际值':undefined}>{children}</span>;}
export function Avatar({player,large=false,size}:{player:Player;large?:boolean;size?:AvatarSize}){const [params]=useSearchParams();const selected=size??(params.get('avatarSize') as AvatarSize||'medium');return <PlayerAvatar player={player} size={large&&selected==='medium'?'large':selected}/>;}
export function PlayerIdentity({player,large=false,size}:{player:Player;large?:boolean;size?:AvatarSize}){const {language}=useLanguage();return <div className="player-identity"><Avatar player={player} large={large} size={size}/><div><strong>{player.name}</strong><span>{language==='en'?`${player.teamAbbreviation} / ${player.position}`:`${player.chineseName} / ${player.teamAbbreviation} / ${player.position}`}</span></div></div>;}
export function Quality({quality,possessions}:{quality:SampleQuality;possessions:number}){const {language}=useLanguage();return <span className={`quality quality-${quality}`} title={language==='en'?'Tier reflects matchup possession count only; it is not a statistical confidence interval.':'仅按样本回合数量分级，不代表统计置信度'}>{quality==='high'?'High':quality==='medium'?'Medium':'Low'} · {number(possessions,0)} {language==='en'?'poss.':'回合'}</span>;}
export function PageHead({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}){const {t}=useLanguage();return <header className="page-head"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{t(title)}</h1><p>{t(description)}</p></div>{children}</header>;}
export function Empty({title='没有符合条件的对位',message='尝试降低最低回合数或清除筛选条件。',children}:{title?:string;message?:string;children?:ReactNode}){const {t}=useLanguage();return <div className="empty"><SlidersHorizontal size={27}/><h3>{t(title)}</h3><p>{t(message)}</p>{children}</div>;}
export function Metric({label,value,unit,basis,help,delta}:{label:string;value:string;unit?:string;basis:string;help:string;delta?:number|null}){const {language,t}=useLanguage();return <article className="metric"><div className="metric-label">{t(label)}<span tabIndex={0} className="hint" aria-label={t(help)}><HelpCircle size={13}/><span role="tooltip">{t(help)}</span></span></div><strong>{value}<small>{unit}</small></strong><p>{t(basis)}</p>{delta!=null&&<span className={`delta ${delta>=0?'positive':'negative'}`}>{delta>=0?<ArrowUp size={13}/>:<ArrowDown size={13}/>} {signed(delta)} {language==='en'?'vs league':'对比联盟'}</span>}</article>;}
export function Field({label,children}:{label:string;children:ReactNode}){const {t}=useLanguage();return <label className="field"><span>{t(label)}</span>{children}</label>;}
export function FilterPanel({filters,onChange,onReset,children,rankings=false}:{filters:Filters;onChange:(patch:Partial<Filters>)=>void;onReset:()=>void;children?:ReactNode;rankings?:boolean}){
 const data=useData();const {language}=useLanguage();const en=language==='en';const pool=getPlayers(data).filter(p=>!filters.team||p.teamId===filters.team);const [params,setParams]=useSearchParams();const locked=params.get('lockedOpponent')==='1';const lockedOpponent=params.get('opponent')??'';
 const sliderValue=filters.minPossessions;
 const slider=(<Field label={`${en?'Minimum matchup possessions':'最低对位回合数'}: ${sliderValue}`}><input className="possessions-slider" type="range" min={10} max={50} step={5} value={sliderValue} list="possession-steps" onChange={e=>onChange({minPossessions:normalizePossessions(Number(e.target.value))})}/><span className="range-ticks">{possessionSteps.map(v=><span key={v}>{v}</span>)}</span><datalist id="possession-steps">{possessionSteps.map(v=><option key={v} value={v}/>)}</datalist></Field>);
 return <details className="filters" open><summary><SlidersHorizontal size={16}/> {en?'Filters':'筛选条件'} <span>{en?'Adjust season, perspective and sample':'调整赛季、视角与样本范围'}</span></summary><div className="filter-grid">
 <div className="filter-group"><strong>{en?'Basic filters':'基础筛选'}</strong>
 <Field label={en?'Season':'赛季'}><select value={filters.season} onChange={e=>onChange({season:e.target.value})}>{data.seasons.map(s=><option key={s}>{s}</option>)}</select></Field>
 <Field label={en?'Season type':'比赛类型'}><select value={filters.type} onChange={e=>onChange({type:e.target.value as Filters['type']})}><option value="regular">{en?'Regular season':'常规赛'}</option><option value="playoffs">{en?'Playoffs':'季后赛'}</option></select></Field>
 <Field label={en?'Team':'球队'}><select value={filters.team} onChange={e=>{const first=getPlayers(data).find(p=>!e.target.value||p.teamId===e.target.value);onChange({team:e.target.value,...(!rankings&&first?{player:first.id}:{})});}}><option value="">{en?'All teams':'所有球队'}</option>{data.teams.map(t=><option key={t.id} value={t.id}>{teamOptionLabel(t,en?'en':'zh')}</option>)}</select></Field>
 {!rankings&&<Field label={en?'Player':'球员'}><select value={filters.player} onChange={e=>onChange({player:e.target.value})}>{pool.map(p=><option key={p.id} value={p.id}>{en?p.name:p.chineseName} · {p.name}</option>)}</select></Field>}</div>
 {!rankings&&<div className="filter-group"><strong>{en?'Matchup filters':'对位筛选'}</strong><Field label={en?'Perspective':'视角'}><select value={filters.perspective} onChange={e=>onChange({perspective:e.target.value as Filters['perspective']})}><option value="offense">{en?'Offense':'进攻视角'}</option><option value="defense">{en?'Defense':'防守视角'}</option></select></Field><Field label={en?'Opponent team':'对手球队'}><select value={filters.opponentTeam} onChange={e=>onChange({opponentTeam:e.target.value})}><option value="">{en?'All opponents':'所有对手'}</option>{data.teams.map(t=><option key={t.id} value={t.id}>{teamOptionLabel(t,en?'en':'zh')}</option>)}</select></Field><Field label={en?'Lock opponent':'锁定对手'}><select value={lockedOpponent} onChange={e=>{const next=new URLSearchParams(params);if(e.target.value)next.set('opponent',e.target.value);else{next.delete('opponent');next.delete('lockedOpponent');}setParams(next,{replace:true});}}><option value="">{en?'Any player':'不限球员'}</option>{data.players.filter(p=>p.id!==filters.player).map(p=><option key={p.id} value={p.id}>{p.name} · {p.teamAbbreviation}</option>)}</select></Field><Button disabled={!lockedOpponent} onClick={()=>{const next=new URLSearchParams(params);if(locked)next.delete('lockedOpponent');else next.set('lockedOpponent','1');setParams(next,{replace:true});}}>{locked?(en?'Unlock opponent':'取消锁定'):(en?'Lock opponent':'锁定对手')}</Button></div>}
 <div className="filter-group"><strong>{en?'Sample filters':'样本筛选'}</strong>
 <Field label={en?'Position':'位置'}><select value={filters.position} onChange={e=>onChange({position:e.target.value})}><option value="">{en?'All positions':'全部位置'}</option>{['G','F','C','G-F','F-C','Unknown'].map(v=><option key={v}>{v}</option>)}</select></Field>
 {slider}
 <Field label={en?'Sample quality':'样本质量'}><select value={filters.quality} onChange={e=>onChange({quality:e.target.value})}><option value="">{en?'All samples':'全部样本'}</option><option value="low">Low &lt; 25 {en?'poss.':'回合'}</option><option value="medium">Medium 25-74 {en?'poss.':'回合'}</option><option value="high">High ≥ 75 {en?'poss.':'回合'}</option></select></Field>
 {children}<Button onClick={onReset} className="filter-reset">{en?'Clear all filters':'清除全部筛选'}</Button></div></div></details>;
}
export function SearchPlayers({onChoose,label='搜索球员',team='',autoFocus=false}:{onChoose:(p:Player)=>void;label?:string;team?:string;autoFocus?:boolean}){const data=useData();const {language}=useLanguage();const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const matches=searchPlayers(data,query,team).slice(0,5);const [index,setIndex]=useState(0);const choose=(p:Player)=>{onChoose(p);setQuery(p.name);setOpen(false);};return <div className="player-search"><label className="field"><span>{label}</span><input autoFocus={autoFocus} value={query} placeholder={language==='en'?'Name, Chinese name, abbreviation or team':'姓名、中文名、缩写或球队'} onFocus={()=>setOpen(query.trim().length>0)} onChange={e=>{setQuery(e.target.value);setOpen(true);setIndex(0);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);return;}if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,Math.max(0,matches.length-1)));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'&&matches[index]){e.preventDefault();choose(matches[index]);}}} aria-controls="player-results" aria-autocomplete="list"/></label>{open&&query.trim()&&<div className="search-results" id="player-results">{matches.length?matches.map((p,i)=><button type="button" className={i===index?'search-result selected':'search-result'} key={p.id} onClick={()=>choose(p)}><PlayerIdentity player={p}/><ArrowUpRight size={18}/></button>):<Empty title={language==='en'?'Player not found': '未找到球员'} message={language==='en'?'Try Curry, Steph, GSW or another team.':'试试 Curry、库里、GSW 或其他球队名称。'}/>}</div>}</div>;}
export function AvatarSizeControl({value,onChange}:{value:AvatarSize;onChange:(value:AvatarSize)=>void}){const {language}=useLanguage();const en=language==='en';return <div className="avatar-size-control" role="group" aria-label={en?'Avatar size':'头像大小'}><span>{en?'Avatar size':'头像大小'}</span>{(['small','medium','large'] as AvatarSize[]).map(size=><Button key={size} variant={value===size?'default':'secondary'} onClick={()=>onChange(size)}>{en?size:size==='small'?'小':size==='medium'?'中':'大'}</Button>)}</div>;}
export function Actions({title,subtitle='',rows,headers,metrics,players=[]}:{title:string;subtitle?:string;headers?:string[];rows?:(string|number|null)[][];metrics:{label:string;value:string}[];players?:Player[]}){const data=useData();const {language}=useLanguage();const en=language==='en';const [status,setStatus]=useState('');return <div className="export-actions"><div className="actions"><Button onClick={async()=>{setStatus(await copyLink()?(en?'Link copied with current filters':'链接已复制，可还原当前筛选'):`${en?'Copy this link: ':'请复制链接：'}${window.location.href}`);}}><Link2 size={15}/>{en?'Copy link':'复制链接'}</Button>{rows&&headers&&<Button onClick={()=>{downloadCSV('courtmatch.csv',headers,rows);setStatus(en?'CSV exported with all current filtered results.':'CSV 已导出，包含当前全部筛选结果。');}}><Download size={15}/>{en?'Export CSV':'导出 CSV'}</Button>}<Button onClick={async()=>{try{await downloadShareCard({title,subtitle,metrics,players,updatedAt:data.updatedAt,mode:data.mode});setStatus(en?'PNG share card generated.':'PNG 分享卡片已生成。');}catch{setStatus(en?'Image export failed. Please try again.':'图片生成失败，请重试。');}}}><ImageDown size={15}/>{en?'Export PNG':'导出 PNG'}</Button></div>{status&&<p className="feedback" role="status">{status}</p>}</div>;}
export function PlayerLink({player,to}:{player:Player;to?:string}){return <Link className="player-link" to={to??`/players/${player.id}`}><PlayerIdentity player={player}/><ArrowUpRight size={15}/></Link>;}
export function Pagination({page,total,pageSize=10,onChange}:{page:number;total:number;pageSize?:number;onChange:(p:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));const {language}=useLanguage();const en=language==='en';return <nav className="pagination" aria-label={en?'Result pagination':'结果分页'}><span>{en?`${total} results · Page ${Math.min(page,pages)} / ${pages}`:`${total} 条结果 · 第 ${Math.min(page,pages)} / ${pages} 页`}</span><Button disabled={page<=1} onClick={()=>onChange(page-1)}>{en?'Previous':'上一页'}</Button><Button disabled={page>=pages} onClick={()=>onChange(page+1)}>{en?'Next':'下一页'}</Button></nav>;}
export function SampleNote({records}:{records:MatchupRecord[]}){const low=records.filter(r=>r.matchupPossessions<25).length;const {language}=useLanguage();const en=language==='en';return <p className="sample-note">{en?(low>0?`${low} records have fewer than 25 possessions. Small samples require caution. `:'')+'Sample tiers describe possession count only; lineups, help defense and schedule also affect results.':(low>0?`${low} 条结果小于 25 回合。Small sample. Interpret with caution. `:'')+'样本等级仅表示回合数量；阵容、协防和赛程都会影响结果。'}</p>;}
export function DataMethodNote(){const data=useData();const status=useDataStatus();const {language}=useLanguage();const en=language==='en';const label=en?(status.state==='live'?'Live data':status.state==='stale'?'Data quality warning':'Demo data'):(status.state==='live'?'实时数据':status.state==='stale'?'数据质量警告':'演示数据');return <section className="data-method-note"><strong>{en?'Data methodology':'数据口径'}</strong><span>{en?'Matchup PPP = points ÷ (field-goal attempts + 0.44 × free-throw attempts + turnovers); points per 100 matchup possessions = points ÷ tracked matchup possessions × 100. These denominators differ and are not interchangeable. A small sample is not a confidence interval or a measure of overall defense.':'Matchup PPP = 得分 ÷（投篮出手 + 0.44 × 罚球出手 + 失误）；每100对位回合得分 = 得分 ÷ 追踪对位回合 × 100。两者分母不同，不可直接互换。低样本不等于统计置信度，也不代表完整防守能力。'}</span><small>{en?'Source: NBA public data / reference feed · Published via GitHub JSON':'数据来源：NBA 官方公开数据 / 参考数据源 · 发布层：GitHub JSON'} · {label} · {en?'Unverified positions remain Unknown':'未确认位置保留为 Unknown'} · {en?'Updated':'更新'} {data.updatedAt.slice(0,10)}</small></section>}
