import { useEffect, useRef, type ReactNode } from 'react';
import { Activity, ArrowUpRight, BarChart3, BookOpen, CalendarDays, Database, FileText, Globe2, History, Rocket, Search, Settings, Shield, SlidersHorizontal, UsersRound, WalletCards, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { Button } from './ui/button';
import { DrawerOverlay } from './DrawerOverlay';
import { SideDrawerItem } from './SideDrawerItem';

export function SideDrawer({ open, onClose, onSearch }: { open: boolean; onClose: () => void; onSearch: () => void }) {
  const panelRef = useRef<HTMLElement>(null); const closeRef = useRef<HTMLButtonElement>(null); const triggerRef = useRef<HTMLElement | null>(null); const location = useLocation();
  useEffect(() => { if (!open) return; triggerRef.current = document.activeElement as HTMLElement; closeRef.current?.focus(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); return; } if (event.key !== 'Tab' || !panelRef.current) return; const focusable = Array.from(panelRef.current.querySelectorAll<HTMLElement>('a[href],button:not([disabled])')); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', onKeyDown); return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = previous; triggerRef.current?.focus(); }; }, [open, onClose]);
  useEffect(() => { if (open) onClose(); }, [location.pathname]);
  const item = (index: string, label: string, description: string, href: string, icon: ReactNode) => <SideDrawerItem key={href} index={index} label={label} description={description} href={href} icon={icon} onNavigate={onClose} />;
  return <><DrawerOverlay open={open} onClick={onClose} /><aside id="courtmatch-side-drawer" ref={panelRef} className={`side-drawer${open ? ' is-open' : ''}`} role="dialog" aria-modal={open} aria-label="CourtMatch 主导航" aria-hidden={!open}><div className="side-drawer-edge" aria-hidden="true" /><header className="side-drawer-header"><div><span className="side-drawer-brand">COURT<span>MATCH</span></span><small>NBA 数据实验室</small></div><Button ref={closeRef} variant="ghost" aria-label="关闭导航" onClick={onClose}><X size={20} /></Button></header><div className="side-drawer-status"><span className="status-dot" />NBA 官方公开数据 <b>GitHub JSON 发布层</b></div><nav className="side-drawer-nav" aria-label="主导航"><p>数据入口</p>{item('01','球员数据','浏览球员赛季数据与个人画像','/players',<UsersRound size={17}/>)}{item('02','球队数据','查看球队效率与球员目录','/teams',<Shield size={17}/>)}{item('03','联盟对位','探索球员之间的直接对位','/matchups',<Activity size={17}/>)}{item('04','球员对位','双人对位与效率比较','/comparison',<SlidersHorizontal size={17}/>)}{item('05','排行榜','按样本门槛查看联盟排名','/rankings',<BarChart3 size={17}/>)}{item('06','打法类型','拆解球员进攻与防守打法','/playtypes',<Database size={17}/>)}{item('07','薪金仓库','当前数据集暂无可验证薪资','/salaries',<WalletCards size={17}/>)}<p>分析与产品</p>{item('08','未来展望','查看公开产品路线图','/future',<Rocket size={17}/>)}{item('09','攻防影响','比较进攻产出与防守压制','/impact',<Shield size={17}/>)}{item('10','每日最佳','查看最近一次可用数据摘要','/daily',<CalendarDays size={17}/>)}{item('11','球员国家','未映射字段保持 Unknown','/countries',<Globe2 size={17}/>)}{item('12','更新日志','查看版本与发布状态','/changelog',<History size={17}/>)}<p>数据与说明</p><button type="button" className="side-drawer-item side-drawer-action" onClick={onSearch}><span className="side-drawer-index">13</span><span className="side-drawer-icon"><Search size={17}/></span><span className="side-drawer-copy"><strong>球员搜索</strong><small>查找球员档案与对位记录</small></span><ArrowUpRight className="side-drawer-arrow" size={16}/></button>{item('14','方法论','指标定义、数据口径和限制','/methodology',<BookOpen size={17}/>)}{item('15','数据来源','查看发布层与覆盖范围','/sources',<FileText size={17}/>)}{item('16','数据状态','切换主题与验证连接状态','/settings',<Settings size={17}/>)}</nav><footer className="side-drawer-footer"><button type="button" onClick={onSearch}><Search size={15}/>打开全局球员搜索 <kbd>⌘ K</kbd></button><span>按 Escape 关闭导航</span></footer></aside></>;
}
