import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Activity, ArrowUpRight, BarChart3, BookOpen, CalendarDays, ChevronDown, Database, FileText, Globe2, History, Rocket, Search, Settings, Shield, UsersRound, WalletCards, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { Button } from './ui/button';
import { DrawerOverlay } from './DrawerOverlay';
import { SideDrawerItem } from './SideDrawerItem';
import { useLanguage } from '../i18n';

export function SideDrawer({ open, onClose, onSearch }: { open: boolean; onClose: () => void; onSearch: () => void }) {
  const panelRef = useRef<HTMLElement>(null); const closeRef = useRef<HTMLButtonElement>(null); const triggerRef = useRef<HTMLElement | null>(null); const location = useLocation(); const { language, t } = useLanguage(); const [expanded, setExpanded] = useState<string | null>(null); const [utility, setUtility] = useState<string | null>(null);
  useEffect(() => { if (!open) return; triggerRef.current = document.activeElement as HTMLElement; closeRef.current?.focus(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); return; } if (event.key !== 'Tab' || !panelRef.current) return; const focusable = Array.from(panelRef.current.querySelectorAll<HTMLElement>('a[href],button:not([disabled])')); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', onKeyDown); return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = previous; triggerRef.current?.focus(); }; }, [open, onClose]);
  useEffect(() => { if (open) onClose(); const path = location.pathname.replace(/^\/courtmatch-analytics(?=\/|$)/, '') || '/'; if (path.startsWith('/player')) setExpanded('球员数据'); else if (path.startsWith('/team') || path === '/rankings' || path === '/playtypes') setExpanded('球队数据'); else if (path.startsWith('/matchup') || path === '/comparison') setExpanded('对位杀手'); else if (path.startsWith('/salary')) setExpanded('薪金仓库'); else if (path.startsWith('/predict') || path === '/methodology' || path === '/sources' || path === '/settings') setExpanded('未来展望'); }, [location.pathname]);
  const item = (index: string, label: string, description: string, href: string, icon: ReactNode) => <SideDrawerItem key={href} index={index} label={t(label)} description={t(description)} href={href} icon={icon} onNavigate={onClose} />;
  const group = (index: string, label: string, icon: ReactNode, links: Array<[string, string, string]>) => <div className="side-drawer-group"><button type="button" className="side-drawer-group-toggle" aria-expanded={expanded === label} onClick={() => setExpanded(expanded === label ? null : label)}><span className="side-drawer-index">{index}</span><span className="side-drawer-icon">{icon}</span><span className="side-drawer-copy"><strong>{t(label)}</strong><small>{t('打开相关分析模块')}</small></span><ChevronDown className={`side-drawer-group-chevron${expanded === label ? ' is-open' : ''}`} size={16} /></button>{expanded === label && <div className="side-drawer-subnav">{links.map(([subIndex, subLabel, href]) => <SideDrawerItem key={href} index={subIndex} label={t(subLabel)} href={href} description={t('进入分析页面')} icon={<ArrowUpRight size={15}/>} onNavigate={onClose} />)}</div>}</div>;
  const utilityPanel = (key: string, label: string, copy: string) => <div className="drawer-utility"><button type="button" aria-expanded={utility === key} onClick={() => setUtility(utility === key ? null : key)}><span>{t(label)}</span><ChevronDown className={utility === key ? 'is-open' : ''} size={14}/></button>{utility === key && <p>{language === 'en' ? ({'支持 CourtMatch':'The project uses public NBA data only. Sponsorship channels will open when the product is ready.','反馈与建议':'Please submit reproducible issues, data sources and page paths through GitHub Issues.','社交媒体':'Public releases and updates are published in the GitHub repository.'}[label] ?? copy) : copy}</p>}</div>;
  return <><DrawerOverlay open={open} onClick={onClose} /><aside id="courtmatch-side-drawer" ref={panelRef} className={`side-drawer${open ? ' is-open' : ''}`} role="dialog" aria-modal={open} aria-label={language==='en'?'CourtMatch main navigation':'CourtMatch 主导航'} aria-hidden={!open}><div className="side-drawer-edge" aria-hidden="true" /><header className="side-drawer-header"><div><span className="side-drawer-brand">COURT<span>MATCH</span></span><small>{t('NBA 数据实验室')}</small></div><Button ref={closeRef} variant="ghost" aria-label={t('关闭导航')} onClick={onClose}><X size={20} /></Button></header><div className="side-drawer-status"><span className="status-dot" />{t('NBA 官方公开数据')} <b>{t('发布层：GitHub JSON')}</b></div><nav className="side-drawer-nav" aria-label={t('主导航')}><p>{t('数据入口')}</p>{group('01','球员数据',<UsersRound size={17}/>,[['01.1','球员总览','/player'],['01.2','球队对比','/player/compare']])}{group('02','球队数据',<Shield size={17}/>,[['02.1','联盟散点','/team'],['02.2','球队攻防','/team/pk'],['02.3','赛季涨幅','/team/compare'],['02.4','排行榜','/rankings'],['02.5','打法类型','/playtypes']])}{group('03','对位杀手',<Activity size={17}/>,[['03.1','联盟对位','/matchup'],['03.2','球员对位','/matchup/player'],['03.3','球员比较','/comparison']])}{group('04','薪金仓库',<WalletCards size={17}/>,[['04.1','薪资总览','/salary'],['04.2','球员页面','/salary/player'],['04.3','球员对比','/salary/compare'],['04.4','球队对比','/salary/team-compare']])}{group('05','未来展望',<Rocket size={17}/>,[['05.1','球员展望','/predict'],['05.2','球员对比','/predict/compare'],['05.3','球队对比','/predict/team-compare'],['05.4','方法论','/methodology'],['05.5','数据来源','/sources'],['05.6','数据状态','/settings']])}<p>{t('分析与产品')}</p>{item('06','攻防影响','比较进攻产出与防守压制','/onoff',<Shield size={17}/>)}{item('07','每日最佳','查看最近一次可用数据摘要','/daily',<CalendarDays size={17}/>)}{item('08','球员国家','未映射字段保持 Unknown','/country',<Globe2 size={17}/>)}{item('09','更新日志','查看版本与发布状态','/changelog',<History size={17}/>)}</nav><footer className="side-drawer-footer"><button type="button" onClick={onSearch}><Search size={15}/>{t('打开全局球员搜索')} <kbd>⌘ K</kbd></button>{utilityPanel('support','支持 CourtMatch','项目目前只使用公开 NBA 数据；支持入口将在正式产品赞助渠道确定后开放。')}{utilityPanel('feedback','反馈与建议','请通过 GitHub Issues 提交可复现的问题、数据来源和页面路径。')}{utilityPanel('social','社交媒体','公开版本与更新记录统一发布在 GitHub 仓库。') }<span>{t('按 Escape 关闭导航')}</span></footer></aside></>;
}
