import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import * as Dialog from '@radix-ui/react-dialog';
import { Search, X, Sun, Moon, ArrowUpRight, Activity, Users, Trophy, Home as HomeIcon } from 'lucide-react';
import { DataGate, useSettings } from './state';
import { Button } from './components/ui/button';
import { SearchPlayers } from './components/Common';
import { HomePage } from './pages/Home';
import { MatchupsPage } from './pages/Matchups';
import { PlayerPage } from './pages/Player';
import { ComparisonPage } from './pages/Comparison';
import { RankingsPage } from './pages/Rankings';
import { InformationPage, SettingsPage } from './pages/Information';
import { PlayTypesPage } from './pages/PlayTypes';
import { NavigationToggle } from './components/NavigationToggle';
import { SideDrawer } from './components/SideDrawer';
import { ChangelogPage, CountriesPage, DailyPage, FuturePage, ImpactPage, PlayerDirectoryPage, SalariesPage, TeamAnalysisPage, TeamComparePage, TeamDetailPage, TeamDirectoryPage } from './pages/Expansion';

const nav=[['/','首页'],['/matchups','联盟对位'],['/comparison','球员比较'],['/rankings','排行榜'],['/playtypes','打法类型'],['/methodology','方法论']];
export function App(){
 const [searchOpen,setSearchOpen]=useState(false);const [drawerOpen,setDrawerOpen]=useState(false);const {theme,setTheme}=useSettings();const location=useLocation();const navigate=useNavigate();
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme:dark)');const apply=()=>{document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;};apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[theme]);
 useEffect(()=>{function onKey(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(v=>!v);}}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 useEffect(()=>{setDrawerOpen(false);window.scrollTo({top:0});const labels:Record<string,string>={'/':'NBA 直接对位分析','/players':'球员数据','/player':'球员数据','/teams':'球队数据','/team':'球队数据','/team/pk':'球队攻防','/team/compare':'球队对比','/matchups':'联盟对位','/matchup':'联盟对位','/comparison':'球员比较','/rankings':'排行榜','/playtypes':'Play Types','/salaries':'薪金仓库','/salary':'薪金仓库','/future':'未来展望','/predict':'未来展望','/impact':'攻防影响','/onoff':'攻防影响','/daily':'每日最佳','/countries':'球员国家','/country':'球员国家','/changelog':'更新日志','/methodology':'方法论','/sources':'数据来源','/settings':'设置'};document.title=`${labels[location.pathname.replace(/\/$/,'')||'/']??'球员数据'} | CourtMatch`;},[location.pathname]);
 useEffect(()=>{const old:Record<string,string>={'#matchups':'/matchups','#comparison':'/comparison','#rankings':'/rankings','#method':'/methodology'};if(location.pathname==='/'&&old[location.hash])navigate(old[location.hash]+location.search,{replace:true});},[location.hash,location.pathname,location.search,navigate]);
 return <><a className="skip-link" href="#main">跳转到主要内容</a><header className="site-header"><NavigationToggle open={drawerOpen} onClick={()=>setDrawerOpen(true)}/><Link className="brand" to="/" aria-label="CourtMatch 首页"><span className="brand-ball" aria-hidden="true"/>COURT<span>MATCH</span><small>ANALYTICS</small></Link><nav className="main-nav" aria-label="主导航">{nav.map(([path,label])=><NavLink key={path} to={path} end={path==='/'}>{label}</NavLink>)}</nav><div className="header-actions"><span className="nba-badge">NBA</span><Button variant="ghost" aria-label="全局搜索" onClick={()=>setSearchOpen(true)}><Search size={18}/><kbd>⌘ K</kbd></Button><Button variant="ghost" aria-label="切换主题" onClick={()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</Button></div></header><SideDrawer open={drawerOpen} onClose={()=>setDrawerOpen(false)} onSearch={()=>{setDrawerOpen(false);setSearchOpen(true)}}/>
 <main id="main" className="main-container"><Routes><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<DataGate><Routes><Route path="/" element={<HomePage onSearch={()=>setSearchOpen(true)}/>}/><Route path="/players" element={<PlayerDirectoryPage/>}/><Route path="/players/:playerId" element={<PlayerPage/>}/><Route path="/player" element={<PlayerDirectoryPage/>}/><Route path="/player/compare" element={<ComparisonPage/>}/><Route path="/teams" element={<TeamDirectoryPage/>}/><Route path="/teams/:teamId" element={<TeamDetailPage/>}/><Route path="/team" element={<TeamDirectoryPage/>}/><Route path="/team/pk" element={<TeamAnalysisPage/>}/><Route path="/team/compare" element={<TeamComparePage/>}/><Route path="/matchups" element={<MatchupsPage/>}/><Route path="/matchups/player" element={<ComparisonPage/>}/><Route path="/matchups/player/:playerId" element={<MatchupsPage detail/>}/><Route path="/matchup" element={<MatchupsPage/>}/><Route path="/matchup/player" element={<ComparisonPage/>}/><Route path="/comparison" element={<ComparisonPage/>}/><Route path="/rankings" element={<RankingsPage/>}/><Route path="/playtypes" element={<PlayTypesPage/>}/><Route path="/playtypes/:playerId" element={<PlayTypesPage detail/>}/><Route path="/salaries" element={<SalariesPage/>}/><Route path="/salary" element={<SalariesPage/>}/><Route path="/salary/player" element={<SalariesPage/>}/><Route path="/salary/compare" element={<SalariesPage/>}/><Route path="/salary/team-compare" element={<SalariesPage/>}/><Route path="/future" element={<FuturePage/>}/><Route path="/predict" element={<FuturePage/>}/><Route path="/predict/compare" element={<FuturePage/>}/><Route path="/predict/team-compare" element={<FuturePage/>}/><Route path="/impact" element={<ImpactPage/>}/><Route path="/onoff" element={<ImpactPage/>}/><Route path="/daily" element={<DailyPage/>}/><Route path="/countries" element={<CountriesPage/>}/><Route path="/country" element={<CountriesPage/>}/><Route path="/changelog" element={<ChangelogPage/>}/><Route path="/methodology" element={<InformationPage/>}/><Route path="/sources" element={<InformationPage sources/>}/><Route path="*" element={<section className="empty"><h1>这个页面没有出现在赛程里</h1><p>检查链接，或返回联盟对位重新开始。</p><Button asChild><Link to="/matchups">探索联盟对位</Link></Button></section>}/></Routes></DataGate>}/></Routes></main>
 <footer className="site-footer"><Link className="brand" to="/">COURT<span>MATCH</span></Link><span>TRACKING THE GAME WITHIN THE GAME</span><div><Link to="/sources">数据来源 <ArrowUpRight size={13}/></Link><Link to="/methodology">指标口径</Link><Link to="/settings">设置</Link></div><small>© {new Date().getFullYear()} CourtMatch Analytics</small></footer>
 <nav className="bottom-nav" aria-label="手机底部导航">{[[HomeIcon,'/','首页'],[Activity,'/matchups','对位'],[Users,'/comparison','比较'],[Trophy,'/rankings','榜单']].map(([Icon,path,label])=>{const I=Icon as typeof HomeIcon;return <NavLink key={String(path)} to={String(path)} end={path==='/'}><I size={19}/><span>{String(label)}</span></NavLink>;})}</nav>
 <Dialog.Root open={searchOpen} onOpenChange={setSearchOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><div className="dialog-header"><Dialog.Title>找到你的球员</Dialog.Title><Dialog.Close asChild><Button variant="ghost" aria-label="关闭搜索"><X size={20}/></Button></Dialog.Close></div><Dialog.Description>支持中英文姓名、球队、缩写；↑ ↓ 选择，Enter 打开球员详情。</Dialog.Description><DataGate><SearchPlayers autoFocus onChoose={p=>{setSearchOpen(false);navigate(`/players/${p.id}`);}}/></DataGate></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
