import { z } from 'zod';
import type { Dataset } from '../types';
import { getHeadToHeadMatchup, getPlayerById, getPlayerMatchups, searchPlayers } from '../api';
import type { BasketballDataProvider, DataStatus } from './contracts';
import { dailyGameLogSchema, matchupSchema, playerSchema, playerStatsSchema, playtypeSchema, teamPlaytypeSchema, teamSchema, teamStatsSchema } from './schemas';

const manifestSchema=z.object({provider:z.literal('github-json'),status:z.enum(['live','recently-updated','stale','demo']),league:z.literal('NBA'),lastUpdated:z.string(),version:z.string(),coverage:z.string(),players:z.string(),teams:z.string(),matchups:z.string(),playerStats:z.string().optional(),playerStatsSourceUpdatedAt:z.string().optional(),daily:z.string().optional(),dailyRecordCount:z.number().nonnegative().optional(),dailySourceUpdatedAt:z.string().optional(),positionMappingRate:z.number().nonnegative().max(100).optional(),playtypes:z.string().optional(),playerPlaytypesSourceUpdatedAt:z.string().optional(),teamPlaytypes:z.string().optional(),teamPlaytypeRecordCount:z.number().nonnegative().optional(),teamPlaytypesSourceUpdatedAt:z.string().optional(),teamStats:z.string().optional(),playerCount:z.number().nonnegative(),matchupRecordCount:z.number().nonnegative(),playtypeRecordCount:z.number().nonnegative().optional(),isDemo:z.boolean()});
async function json(url:string,signal:AbortSignal){const response=await fetch(url,{headers:{Accept:'application/json'},signal,cache:'no-cache'});if(!response.ok)throw new Error(`数据请求失败 (${response.status})`);return response.json();}
export class GithubJsonProvider implements BasketballDataProvider {
  private manifest?:z.infer<typeof manifestSchema>;private dataset?:Dataset;
  constructor(private readonly baseUrl:string){}
  private url(file:string){return `${this.baseUrl.replace(/\/$/,'')}/${file.replace(/^\//,'')}`;}
  private async loadManifest(){if(this.manifest)return this.manifest;const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),8000);try{this.manifest=manifestSchema.parse(await json(this.url('manifest.json'),controller.signal));return this.manifest;}finally{window.clearTimeout(timeout);}}
  private async load(){if(this.dataset)return;const manifest=await this.loadManifest();const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),20000);try{const [players,teams,matchups,playerStats,daily,playtypes,teamPlaytypes,teamStats]=await Promise.all([json(this.url(manifest.players),controller.signal).then(value=>z.array(playerSchema).parse(value)),json(this.url(manifest.teams),controller.signal).then(value=>z.array(teamSchema).parse(value)),json(this.url(manifest.matchups),controller.signal).then(value=>z.array(matchupSchema).parse(value)),manifest.playerStats?json(this.url(manifest.playerStats),controller.signal).then(value=>z.array(playerStatsSchema).parse(value)):Promise.resolve([]),manifest.daily?json(this.url(manifest.daily),controller.signal).then(value=>z.array(dailyGameLogSchema).parse(value)):Promise.resolve([]),manifest.playtypes?json(this.url(manifest.playtypes),controller.signal).then(value=>z.array(playtypeSchema).parse(value)):Promise.resolve([]),manifest.teamPlaytypes?json(this.url(manifest.teamPlaytypes),controller.signal).then(value=>z.array(teamPlaytypeSchema).parse(value)):Promise.resolve([]),manifest.teamStats?json(this.url(manifest.teamStats),controller.signal).then(value=>z.array(teamStatsSchema).parse(value)):Promise.resolve([])]);const state=manifest.status==='recently-updated'?'stale':manifest.status;this.dataset={players,teams,matchups,playerStats,daily,playtypes,teamPlaytypes,teamStats,manifest:{provider:manifest.provider,status:state,league:'NBA',season:[...new Set(matchups.map(row=>row.season))].sort().reverse()[0]??'',lastUpdated:manifest.lastUpdated,version:manifest.version,playerCount:manifest.playerCount,matchupRecordCount:manifest.matchupRecordCount,playtypeRecordCount:manifest.playtypeRecordCount??playtypes.length,dailyRecordCount:manifest.dailyRecordCount??daily.length,playerStatsSourceUpdatedAt:manifest.playerStatsSourceUpdatedAt,dailySourceUpdatedAt:manifest.dailySourceUpdatedAt,positionMappingRate:manifest.positionMappingRate,playerPlaytypesSourceUpdatedAt:manifest.playerPlaytypesSourceUpdatedAt,teamPlaytypeRecordCount:manifest.teamPlaytypeRecordCount??teamPlaytypes.length,teamPlaytypesSourceUpdatedAt:manifest.teamPlaytypesSourceUpdatedAt,teamCount:teams.length,isDemo:manifest.isDemo,source:`GitHub JSON · ${this.baseUrl}`},source:`GitHub JSON · ${this.baseUrl}`,updatedAt:manifest.lastUpdated,mode:manifest.isDemo?'demo':'live',seasons:[...new Set(matchups.map(row=>row.season))].sort().reverse()};}finally{window.clearTimeout(timeout);}}
  async getDataset(){await this.load();return this.dataset!;}
  async getDataStatus():Promise<DataStatus>{const m=await this.loadManifest();return {provider:'github-json',state:m.status,lastUpdated:m.lastUpdated,version:m.version,coverage:m.coverage,isDemo:m.isDemo};}
  async getPlayers(){return (await this.getDataset()).players;}
  async getTeams(){return (await this.getDataset()).teams;}
  async getMatchups(){return (await this.getDataset()).matchups;}
  async getPlayerById(id:string){return getPlayerById(await this.getDataset(),id);}
  async searchPlayers(query:string){return searchPlayers(await this.getDataset(),query);}
  async getPlayerStats(){return (await this.getDataset()).playerStats;}
  async getPlayerMatchups(playerId:string,filters={}){return getPlayerMatchups(await this.getDataset(),playerId,filters);}
  async getHeadToHead(playerA:string,playerB:string,filters={}){return getHeadToHeadMatchup(await this.getDataset(),playerA,playerB,filters);}
  async getPlayerPlayTypes(){return (await this.getDataset()).playtypes;}
  async getTeamStats(){return (await this.getDataset()).teamStats;}
  async getTeamPlayTypes(teamId:string,filters:Partial<import('../types').Filters>={}){return (await this.getDataset()).teamPlaytypes.filter(row=>row.teamId===teamId&&(!filters.season||row.season===filters.season)&&(!filters.type||row.seasonType===filters.type));}
  async getDataManifest(){return (await this.getDataset()).manifest;}
}
