import { z } from 'zod';

const league=z.literal('NBA');
const seasonType=z.enum(['regular','playoffs']);
const numeric=z.number().finite();

export const playerSchema=z.object({id:z.string().min(1),name:z.string().min(1),chineseName:z.string().min(1),aliases:z.array(z.string()),shortName:z.string().min(1),teamId:z.string().min(1),teamName:z.string().min(1),teamAbbreviation:z.string().min(1),position:z.enum(['G','F','C','G-F','F-C']),height:z.string(),weight:numeric,jerseyNumber:z.string(),headshotUrl:z.string(),league});
export const teamSchema=z.object({id:z.string().min(1),name:z.string().min(1),chineseName:z.string().min(1),abbreviation:z.string().min(1),logoUrl:z.string()});
export const matchupSchema=z.object({id:z.string().min(1),offensivePlayerId:z.string().min(1),defensivePlayerId:z.string().min(1),season:z.string().min(1),seasonType,league,matchupPossessions:numeric.nonnegative(),points:numeric,fieldGoalAttempts:numeric.nonnegative(),fieldGoalsMade:numeric.nonnegative(),threePointAttempts:numeric.nonnegative(),threePointMade:numeric.nonnegative(),freeThrowAttempts:numeric.nonnegative(),freeThrowsMade:numeric.nonnegative(),turnovers:numeric.nonnegative(),assists:numeric.optional(),rebounds:numeric.optional(),updatedAt:z.string().min(1)});
export const playerStatsSchema=z.object({playerId:z.string().min(1),season:z.string().min(1),seasonType,gamesPlayed:numeric.nonnegative(),pointsPerGame:numeric,reboundsPerGame:numeric,assistsPerGame:numeric,stealsPerGame:numeric,blocksPerGame:numeric,fieldGoalPercentage:numeric,threePointPercentage:numeric,freeThrowPercentage:numeric,trueShootingPercentage:numeric.optional(),updatedAt:z.string().min(1)});
export const playtypeSchema=z.object({playerId:z.string().min(1),playType:z.enum(['Isolation','Transition','PRBallHandler','PRRollman','Postup','Spotup','Handoff','Cut','OffScreen','OffRebound','Misc']),grouping:z.enum(['offensive','defensive']),possessions:numeric.nonnegative(),pointsPerPossession:numeric.nullable(),percentile:numeric.nullable(),season:z.string().min(1),seasonType,updatedAt:z.string().min(1)});
export const teamStatsSchema=z.object({teamId:z.string().min(1),season:z.string().min(1),seasonType,wins:numeric.optional(),losses:numeric.optional(),offensiveRating:numeric.optional(),defensiveRating:numeric.optional(),pace:numeric.optional(),updatedAt:z.string().min(1)});
export const rankingRowSchema=z.object({playerId:z.string().min(1),season:z.string().regex(/^\d{4}-\d{2}$/),seasonType,possessions:numeric.nonnegative(),efficiency:numeric.nullable(),rank:z.number().int().positive(),sampleQuality:z.enum(['low','medium','high']),updatedAt:z.string().datetime({offset:true})});
export const manifestSchema=z.object({provider:z.enum(['mock','github-json','supabase']),status:z.enum(['live','demo','stale','error','unavailable']),league,lastUpdated:z.string().datetime({offset:true}),version:z.string().min(1),coverage:z.string().min(1),players:z.string().min(1),teams:z.string().min(1),matchups:z.string().min(1),playerStats:z.string().optional(),playtypes:z.string().optional(),teamStats:z.string().optional(),rankings:z.string().optional(),playerCount:z.number().int().nonnegative(),teamCount:z.number().int().nonnegative().optional(),matchupRecordCount:z.number().int().nonnegative(),playtypeRecordCount:z.number().int().nonnegative().optional(),missingRecordCount:z.number().int().nonnegative().default(0),invalidRecordCount:z.number().int().nonnegative().default(0),possessionsAreEstimated:z.boolean().default(false),possessionMethod:z.enum(['official-field','derived','unknown']).default('unknown'),possessionConfidence:z.enum(['high','medium','low']).default('low'),isDemo:z.boolean()});
export type DatasetValidation={valid:boolean;errors:string[]};
export function validateDatasetReferences(input:{players:unknown;teams:unknown;matchups:unknown;playtypes?:unknown;manifest:unknown}):DatasetValidation{const errors:string[]=[];const players=z.array(playerSchema).safeParse(input.players);const teams=z.array(teamSchema).safeParse(input.teams);const matchups=z.array(matchupSchema).safeParse(input.matchups);const playtypes=z.array(playtypeSchema).safeParse(input.playtypes??[]);const manifest=manifestSchema.safeParse(input.manifest);for(const [label,result] of [['players',players],['teams',teams],['matchups',matchups],['playtypes',playtypes],['manifest',manifest]] as const)if(!result.success)errors.push(`${label}: ${result.error.issues.map(issue=>issue.path.join('.')||issue.message).join(', ')}`);if(!players.success||!teams.success||!matchups.success)return {valid:false,errors};const playerIds=new Set<string>();for(const player of players.data){if(playerIds.has(player.id))errors.push(`duplicate player id: ${player.id}`);playerIds.add(player.id);}const teamIds=new Set<string>();for(const team of teams.data){if(teamIds.has(team.id))errors.push(`duplicate team id: ${team.id}`);teamIds.add(team.id);}const matchupIds=new Set<string>();for(const row of matchups.data){if(matchupIds.has(row.id))errors.push(`duplicate matchup id: ${row.id}`);matchupIds.add(row.id);if(!playerIds.has(row.offensivePlayerId))errors.push(`missing offensive player: ${row.offensivePlayerId}`);if(!playerIds.has(row.defensivePlayerId))errors.push(`missing defensive player: ${row.defensivePlayerId}`);}for(const player of players.data)if(!teamIds.has(player.teamId))errors.push(`missing player team: ${player.teamId}`);if(playtypes.success)for(const row of playtypes.data)if(!playerIds.has(row.playerId))errors.push(`missing playtype player: ${row.playerId}`);return {valid:errors.length===0,errors};}
